import maplibregl, { type GeoJSONSource, type MapMouseEvent } from "maplibre-gl";
import "maplibre-gl/dist/maplibre-gl.css";
import "./canvassing.css";

type Household = { household_id:string; address_id:string; structure_id:string|null; label:string; civic_number:string; street:string; unit:string; lon:number; lat:number; association_status:string; status:string; flyer_delivered:number; door_knocked:number; visit_count:number };
type RouteStop={id:string;route_id:string;household_id:string;sequence:number;completed_at:string|null;skipped:number;label:string;lon:number;lat:number};
type State = { households:Household[]; routes:Array<{id:string;name:string;status:string;stop_count:number;completed_count:number}>; route_stops:RouteStop[]; summary:Record<string,number> };
const statusColors:Record<string,string>={untouched:"#8b9297",flyer_delivered:"#edc949",knocked_no_answer:"#4e79a7",conversation:"#45a36d",revisit:"#e88935",supportive:"#45a36d",undecided:"#edc949",opposed:"#b34d4d",volunteer_interest:"#8f63b8",lawn_sign_interest:"#8f63b8",inaccessible:"#b34d4d",vacant:"#727b80",no_campaign_material_requested:"#8e2f3d"};
const fetchJson=async<T>(url:string,init?:RequestInit):Promise<T>=>{const role=document.querySelector<HTMLInputElement>("#volunteer-mode")?.checked?"volunteer":"candidate";const response=await fetch(url,{...init,headers:{"content-type":"application/json","x-canvass-role":role,...(init?.headers??{})}});if(!response.ok)throw new Error(await response.text());return response.json()};
const geo=async(url:string)=>fetchJson<any>(url);

export async function canvassingMain(){
  document.title="Owen Sound Canvassing | Living Region";
  document.body.innerHTML=`<div class="canvass-shell">
    <header><div><strong>Owen Sound Canvassing</strong><span>Private campaign workspace</span></div><nav><button id="coverage-toggle">Coverage</button><button id="print-route">Print</button><a class="button" href="/api/canvassing/export/routes.csv">Export CSV</a><button id="import-open">Import</button></nav></header>
    <aside class="summary" id="summary"></aside><main id="canvass-map"></main>
    <section class="drawer" id="drawer"><div class="empty"><strong>Select a roof or address</strong><span>Click households to inspect them or add them to a route.</span></div></section>
    <footer><div class="route-builder"><input id="route-name" placeholder="New route name"><select id="street-side"><option value="">Both sides</option><option value="left">Left side</option><option value="right">Right side</option></select><button id="create-route">Create <span id="selection-count">0</span></button><button id="bulk-flyer">Flyer selected</button></div><div class="route-run"><select id="active-route"><option value="">Choose route</option></select><button id="previous-stop">Previous</button><button id="next-stop">Next</button><span id="route-progress"></span></div><label><input id="volunteer-mode" type="checkbox"> Volunteer delivery mode</label><label>Status <select id="status-filter"><option value="all">All</option>${Object.keys(statusColors).map(s=>`<option value="${s}">${s.replaceAll('_',' ')}</option>`).join('')}</select></label></footer>
    <dialog id="import-dialog"><form method="dialog"><h2>Import existing records</h2><p>CSV fields: address, date_met, person_name, outcome, issues, notes, follow_up, support_level.</p><input id="csv-file" type="file" accept=".csv,text/csv"><menu><button value="cancel">Cancel</button><button id="import-submit" value="default">Import</button></menu></form></dialog>
    <div class="toast" id="toast"></div></div>`;
  let state=await fetchJson<State>("/api/canvassing/state");
  const [structures,addresses,roads,boundary]=await Promise.all([geo("/canvassing/structures.geojson"),geo("/canvassing/addresses.geojson"),geo("/canvassing/roads.geojson"),geo("/canvassing/boundary.geojson")]);
  const byStructure=new Map<string,Household[]>(); for(const h of state.households){if(h.structure_id)byStructure.set(h.structure_id,[...(byStructure.get(h.structure_id)??[]),h]);}
  const selected=new Set<string>(); let active:Household|undefined; let coverage=false; let routeIndex=0;
  const statusRank=(s:string)=>["untouched","flyer_delivered","knocked_no_answer","conversation","undecided","supportive","opposed","revisit","volunteer_interest","lawn_sign_interest","vacant","inaccessible","no_campaign_material_requested"].indexOf(s);
  for(const f of structures.features){const homes=byStructure.get(f.properties.structure_id)??[];f.properties.household_count=homes.length;f.properties.status=homes.sort((a,b)=>statusRank(b.status)-statusRank(a.status))[0]?.status??"untouched";}
  for(const f of addresses.features){const home=state.households.find(h=>h.address_id===f.properties.address_id);f.properties.household_id=home?.household_id;f.properties.status=home?.status??"untouched";}
  const map=new maplibregl.Map({container:"canvass-map",center:[-80.943,44.567],zoom:13.3,minZoom:11,maxZoom:20,style:{version:8,sources:{},layers:[{id:"background",type:"background",paint:{"background-color":"#eef0eb"}}]}});
  map.addControl(new maplibregl.NavigationControl({showCompass:false}),"bottom-right");
  let labelMarkers:maplibregl.Marker[]=[];
  const updateLabels=()=>{labelMarkers.forEach(marker=>marker.remove());labelMarkers=[];if(map.getZoom()<14)return;const bounds=map.getBounds(),seen=new Set<string>();for(const feature of roads.features){const name=String(feature.properties.name??"");if(!name||seen.has(name))continue;const line=feature.geometry.type==="MultiLineString"?feature.geometry.coordinates[0]:feature.geometry.coordinates;const point=line[Math.floor(line.length/2)];if(!bounds.contains(point))continue;seen.add(name);const element=document.createElement("span");element.className="road-name";element.textContent=name;labelMarkers.push(new maplibregl.Marker({element}).setLngLat(point).addTo(map));if(labelMarkers.length>=70)break;}if(map.getZoom()>=17){for(const feature of addresses.features){const point=feature.geometry.coordinates;if(!bounds.contains(point))continue;const element=document.createElement("span");element.className="address-number";element.textContent=String(feature.properties.civic_number??"");labelMarkers.push(new maplibregl.Marker({element}).setLngLat(point).addTo(map));if(labelMarkers.length>=180)break;}}};
  map.on("moveend",updateLabels);map.on("zoomend",updateLabels);
  map.on("load",()=>{
    map.addSource("boundary",{type:"geojson",data:boundary});map.addLayer({id:"boundary",type:"line",source:"boundary",paint:{"line-color":"#1e5b4a","line-width":2,"line-dasharray":[3,2]}});
    map.addSource("roads",{type:"geojson",data:roads});map.addLayer({id:"road-casing",type:"line",source:"roads",paint:{"line-color":"#c8ccc8","line-width":["interpolate",["linear"],["zoom"],12,1.5,17,8]}});map.addLayer({id:"roads",type:"line",source:"roads",paint:{"line-color":"#fff","line-width":["interpolate",["linear"],["zoom"],12,.7,17,5]}});
    const statusExpression=["match",["get","status"],...Object.entries(statusColors).flat(),"#8b9297"] as any;
    map.addSource("structures",{type:"geojson",data:structures,promoteId:"structure_id"});map.addLayer({id:"structures",type:"fill",source:"structures",minzoom:13,paint:{"fill-color":statusExpression,"fill-opacity":["case",[">",["get","household_count"],0],.82,.32],"fill-outline-color":"#4f5754"}});
    map.addSource("addresses",{type:"geojson",data:addresses,cluster:true,clusterRadius:42,clusterMaxZoom:14,promoteId:"address_id"});map.addLayer({id:"address-clusters",type:"circle",source:"addresses",filter:["has","point_count"],maxzoom:15,paint:{"circle-color":"#275d50","circle-radius":["step",["get","point_count"],14,50,20,200,28],"circle-opacity":.86}});map.addLayer({id:"address-points",type:"circle",source:"addresses",filter:["!",["has","point_count"]],minzoom:14,paint:{"circle-radius":["interpolate",["linear"],["zoom"],14,2.5,18,5],"circle-color":statusExpression,"circle-stroke-color":"#fff","circle-stroke-width":1}});
    map.addSource("active-route",{type:"geojson",data:{type:"FeatureCollection",features:[]}});map.addLayer({id:"active-route-line",type:"line",source:"active-route",filter:["==",["geometry-type"],"LineString"],paint:{"line-color":"#182b68","line-width":4,"line-dasharray":[2,1]}});map.addLayer({id:"active-route-stops",type:"circle",source:"active-route",filter:["==",["geometry-type"],"Point"],paint:{"circle-color":"#fff","circle-stroke-color":"#182b68","circle-stroke-width":3,"circle-radius":6}});
    map.on("click","structures",pickStructure);map.on("click","address-points",pickAddress);map.on("click","address-clusters",async e=>{const feature=e.features?.[0];if(!feature)return;const zoom=await (map.getSource("addresses") as GeoJSONSource).getClusterExpansionZoom(Number(feature.properties?.cluster_id));map.easeTo({center:(feature.geometry as any).coordinates,zoom});});
    for(const layer of ["structures","address-points"]){map.on("mouseenter",layer,()=>map.getCanvas().style.cursor="pointer");map.on("mouseleave",layer,()=>map.getCanvas().style.cursor="");}
    updateLabels();
  });
  const toast=(message:string)=>{const el=document.querySelector<HTMLDivElement>("#toast")!;el.textContent=message;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),2200)};
  function renderSummary(){const s=state.summary,total=Number(s.total_households);document.querySelector("#summary")!.innerHTML=`<dl><div><dt>Households</dt><dd>${total.toLocaleString()}</dd></div><div><dt>Flyers</dt><dd>${s.flyers_delivered}</dd></div><div><dt>Knocked</dt><dd>${s.doors_knocked}</dd></div><div><dt>Answers</dt><dd>${s.answers}</dd></div><div><dt>Talked</dt><dd>${s.conversations}</dd></div><div><dt>Revisit</dt><dd>${s.revisits}</dd></div><div><dt>Untouched</dt><dd>${s.untouched_households}</dd></div><div><dt>Per hour</dt><dd>${s.households_completed_per_hour}</dd></div><div><dt>Answer rate</dt><dd>${s.answer_rate}%</dd></div></dl><div class="legend">${Object.entries(statusColors).map(([s,c])=>`<span><i style="background:${c}"></i>${s.replaceAll('_',' ')}</span>`).join('')}</div>`;renderRoutes();}
  function pickStructure(e:MapMouseEvent&{features?:maplibregl.MapGeoJSONFeature[]}){const id=String(e.features?.[0]?.properties?.structure_id??"");const homes=byStructure.get(id)??[];if(!homes.length)return toast("No civic address is linked to this structure");showHouseholds(homes);}
  function pickAddress(e:MapMouseEvent&{features?:maplibregl.MapGeoJSONFeature[]}){const id=String(e.features?.[0]?.properties?.household_id??"");const home=state.households.find(h=>h.household_id===id);if(home)showHouseholds([home]);}
  function showHouseholds(homes:Household[]){active=homes[0];const volunteer=(document.querySelector<HTMLInputElement>("#volunteer-mode")!).checked;document.querySelector("#drawer")!.innerHTML=`<div class="drawer-head"><div><small>${homes.length>1?`${homes.length} units at structure`:"Household"}</small><h2>${active.label||"Address needs review"}</h2><span>${active.association_status.replaceAll('_',' ')} · ${active.visit_count} visits</span></div><button id="add-selection">${selected.has(active.household_id)?"Remove":"Add to route"}</button></div>${homes.length>1?`<div class="unit-tabs">${homes.map(h=>`<button data-household="${h.household_id}">${h.unit||h.label}</button>`).join('')}</div>`:""}<div class="quick-actions"><button data-outcome="flyer_delivered">Flyer</button><button data-outcome="knocked_no_answer">No answer</button><button data-outcome="conversation">Talked</button><button data-outcome="revisit">Revisit</button><button data-outcome="inaccessible">Skip</button></div>${volunteer?"":`<div class="private-fields"><label>Outcome<select id="outcome">${Object.keys(statusColors).map(s=>`<option ${s===active!.status?'selected':''} value="${s}">${s.replaceAll('_',' ')}</option>`).join('')}</select></label><label>Issues<input id="issues" placeholder="housing; transit; affordability"></label><label>Private notes<textarea id="notes" rows="3"></textarea></label><label>Follow-up<input id="follow-up"></label><label>Date<input id="follow-date" type="date"></label><button id="save-detail">Save visit</button></div>`}`;
    document.querySelector("#add-selection")!.addEventListener("click",()=>{if(!active)return;selected.has(active.household_id)?selected.delete(active.household_id):selected.add(active.household_id);updateSelection();showHouseholds(homes)});
    document.querySelectorAll<HTMLElement>("[data-household]").forEach(el=>el.addEventListener("click",()=>{active=homes.find(h=>h.household_id===el.dataset.household);showHouseholds(homes)}));
    document.querySelectorAll<HTMLElement>("[data-outcome]").forEach(el=>el.addEventListener("click",()=>saveVisit(el.dataset.outcome!)));
    document.querySelector("#save-detail")?.addEventListener("click",()=>saveVisit((document.querySelector<HTMLSelectElement>("#outcome")!).value,true));
  }
  async function saveVisit(outcome:string,detailed=false){if(!active)return;await fetchJson("/api/canvassing/visits",{method:"POST",body:JSON.stringify({household_id:active.household_id,route_id:document.querySelector<HTMLSelectElement>("#active-route")!.value||null,outcome,flyer_delivered:outcome==="flyer_delivered",door_knocked:["knocked_no_answer","conversation","revisit","supportive","undecided","opposed","volunteer_interest","lawn_sign_interest"].includes(outcome),conversation_occurred:["conversation","supportive","undecided","opposed","volunteer_interest","lawn_sign_interest"].includes(outcome),issue_categories:detailed?(document.querySelector<HTMLInputElement>("#issues")?.value??"").split(';').filter(Boolean):[],notes:detailed?document.querySelector<HTMLTextAreaElement>("#notes")?.value:"",follow_up_action:detailed?document.querySelector<HTMLInputElement>("#follow-up")?.value:null,follow_up_date:detailed?document.querySelector<HTMLInputElement>("#follow-date")?.value:null,source:(document.querySelector<HTMLInputElement>("#volunteer-mode")!).checked?"volunteer":"candidate"})});await refresh();toast("Visit appended");}
  async function refresh(){state=await fetchJson<State>("/api/canvassing/state");byStructure.clear();for(const h of state.households){if(h.structure_id)byStructure.set(h.structure_id,[...(byStructure.get(h.structure_id)??[]),h]);if(active?.household_id===h.household_id)active=h;}for(const feature of structures.features){const homes=byStructure.get(feature.properties.structure_id)??[];feature.properties.status=homes.sort((a,b)=>statusRank(b.status)-statusRank(a.status))[0]?.status??"untouched";}for(const feature of addresses.features){feature.properties.status=state.households.find(h=>h.address_id===feature.properties.address_id)?.status??"untouched";}(map.getSource("structures") as GeoJSONSource|undefined)?.setData(structures);(map.getSource("addresses") as GeoJSONSource|undefined)?.setData(addresses);renderSummary();if(active)showHouseholds([active]);}
  function renderRoutes(){const select=document.querySelector<HTMLSelectElement>("#active-route")!,current=select.value;select.innerHTML='<option value="">Choose route</option>'+state.routes.map(r=>`<option value="${r.id}">${r.name}</option>`).join('');select.value=current;const stops=state.route_stops.filter(s=>s.route_id===current),done=stops.filter(s=>s.completed_at).length;let distance=0;for(let i=1;i<stops.length;i++){const a=stops[i-1],b=stops[i],lat=(a.lat+b.lat)/2*Math.PI/180,x=(b.lon-a.lon)*111320*Math.cos(lat),y=(b.lat-a.lat)*111320;distance+=Math.hypot(x,y);}document.querySelector("#route-progress")!.textContent=current?`${done}/${stops.length} · ${stops.length-done} flyers · ${(distance/1000).toFixed(1)} km`:"";const features:any[]=[];if(stops.length>1)features.push({type:"Feature",properties:{},geometry:{type:"LineString",coordinates:stops.map(s=>[s.lon,s.lat])}});features.push(...stops.map(s=>({type:"Feature",properties:{completed:Boolean(s.completed_at),sequence:s.sequence},geometry:{type:"Point",coordinates:[s.lon,s.lat]}})));(map.getSource("active-route") as GeoJSONSource|undefined)?.setData({type:"FeatureCollection",features});}
  function navigateRoute(delta:number){const route=document.querySelector<HTMLSelectElement>("#active-route")!.value,stops=state.route_stops.filter(s=>s.route_id===route);if(!stops.length)return;routeIndex=Math.max(0,Math.min(stops.length-1,routeIndex+delta));if(delta===1){const next=stops.findIndex((s,index)=>index>=routeIndex&&!s.completed_at);if(next>=0)routeIndex=next;}const stop=stops[routeIndex],home=state.households.find(h=>h.household_id===stop.household_id);if(home){showHouseholds([home]);map.easeTo({center:[home.lon,home.lat],zoom:18});}}
  function updateSelection(){document.querySelector("#selection-count")!.textContent=String(selected.size);}
  const orderGeographically=(homes:Household[])=>{const remaining=[...homes].sort((a,b)=>a.street.localeCompare(b.street)||a.civic_number.localeCompare(b.civic_number,undefined,{numeric:true})),ordered=remaining.splice(0,1);while(remaining.length){const current=ordered.at(-1)!;let best=0,bestDistance=Infinity;remaining.forEach((candidate,index)=>{const x=(candidate.lon-current.lon)*.72,y=candidate.lat-current.lat,d=x*x+y*y;if(d<bestDistance){best=index;bestDistance=d;}});ordered.push(remaining.splice(best,1)[0]);}return ordered;};
  document.querySelector("#create-route")!.addEventListener("click",async()=>{if(!selected.size)return toast("Select households first");const homes=orderGeographically([...selected].map(id=>state.households.find(h=>h.household_id===id)!));const result=await fetchJson<{id:string}>("/api/canvassing/routes",{method:"POST",body:JSON.stringify({name:(document.querySelector<HTMLInputElement>("#route-name")!).value,street_side:(document.querySelector<HTMLSelectElement>("#street-side")!).value,household_ids:homes.map(h=>h.household_id)})});selected.clear();updateSelection();await refresh();toast(`Route created: ${result.id.slice(0,8)}`)});
  document.querySelector("#bulk-flyer")!.addEventListener("click",async()=>{for(const household_id of selected)await fetchJson("/api/canvassing/visits",{method:"POST",body:JSON.stringify({household_id,outcome:"flyer_delivered",flyer_delivered:true,door_knocked:false,source:"volunteer"})});selected.clear();updateSelection();await refresh();toast("Selected addresses marked flyer delivered")});
  document.querySelector("#active-route")!.addEventListener("change",()=>{routeIndex=0;renderRoutes();navigateRoute(0)});document.querySelector("#previous-stop")!.addEventListener("click",()=>navigateRoute(-1));document.querySelector("#next-stop")!.addEventListener("click",()=>navigateRoute(1));
  document.querySelector("#status-filter")!.addEventListener("change",e=>{const value=(e.target as HTMLSelectElement).value;map.setFilter("structures",value==="all"?null:["==",["get","status"],value]);map.setFilter("address-points",value==="all"?["!",["has","point_count"]]:["all",["!",["has","point_count"]],["==",["get","status"],value]])});
  document.querySelector("#coverage-toggle")!.addEventListener("click",()=>{coverage=!coverage;map.easeTo({zoom:coverage?12.2:15});toast(coverage?"Coverage aggregation enabled":"Household view enabled")});
  document.querySelector("#print-route")!.addEventListener("click",()=>window.print());
  const dialog=document.querySelector<HTMLDialogElement>("#import-dialog")!;document.querySelector("#import-open")!.addEventListener("click",()=>dialog.showModal());document.querySelector("#import-submit")!.addEventListener("click",async e=>{e.preventDefault();const file=document.querySelector<HTMLInputElement>("#csv-file")!.files?.[0];if(!file)return;const response=await fetch("/api/canvassing/import.csv",{method:"POST",headers:{"content-type":"text/csv"},body:await file.text()});if(!response.ok)throw new Error(await response.text());dialog.close();await refresh();toast("CSV import complete")});
  renderSummary();
}
