// SPDX-License-Identifier: AGPL-3.0-or-later
import { average } from '../util/math.mjs';

export function calculateSettlementMetrics(world, scenario, year, context) {
  const annualCaloriesPerPerson = scenario.annualCaloriesPerPerson ?? context.constants?.annualCaloriesPerPerson ?? 900_000;

  const soilCarbonAverage = average(world.patches.map((patch) => patch.soil.carbon), 0);
  const supportableTotalPopulation = context.producedCalories / annualCaloriesPerPerson;
  const urbanPopulationSupportableByFood = Math.max(0, supportableTotalPopulation - context.populationRural);

  const regionalMetrics = {
    year,
    producedCalories: context.producedCalories,
    consumedCalories: context.consumedCalories,
    foodSurplusCalories: context.foodSurplusCalories,
    urbanPopulationSupportableByFood,
    percentLabourInFood: context.percentAvailableLabourSuppliedToFood,
    percentAvailableLabourDemandedByFood: context.percentAvailableLabourDemandedByFood,
    percentAvailableLabourSuppliedToFood: context.percentAvailableLabourSuppliedToFood,
    percentTotalLabourDemandFromFood: context.percentTotalLabourDemandFromFood,
    foodLabourDemandDays: context.foodLabourDemandDays,
    foodLabourSuppliedDays: context.foodLabourSuppliedDays,
    foodLabourUnmetDays: context.foodLabourUnmetDays,
    labourAvailableDays: context.labourAvailableDays,
    labourDemandFoodDays: context.foodLabourDemandDays,
    labourDemandFuelDays: context.labourDemandFuelDays,
    labourDemandMaintenanceDays: context.labourDemandMaintenanceDays,
    labourDemandCareDays: context.labourDemandCareDays,
    labourDemandTransportDays: context.labourDemandTransportDays,
    labourUnmetTransportDays: context.labourUnmetTransportDays,
    labourSuppliedFoodDays: context.foodLabourSuppliedDays,
    labourSuppliedFuelDays: context.labourSuppliedFuelDays,
    labourSuppliedMaintenanceDays: context.labourSuppliedMaintenanceDays,
    labourSuppliedCareDays: context.labourSuppliedCareDays,
    labourSuppliedTransportDays: context.labourSuppliedTransportDays,
    labourUnmetTotalDays: context.labourUnmetTotalDays,
    labourDeficitDays: context.labourDeficitDays,
    labourCoverageRatio: context.labourCoverageRatio,
    maintenanceCoverageRatio: context.maintenanceCoverageRatio,
    heatDemandKwh: context.heatDemandKwh,
    woodHeatSupplyKwh: context.woodHeatSupplyKwh,
    electricHeatSupplyKwh: context.electricHeatSupplyKwh,
    fossilHeatSupplyKwh: context.fossilHeatSupplyKwh,
    heatingEnergyDeficitKwh: context.heatingEnergyDeficitKwh,
    transportFuelDemandLitre: context.transportFuelDemandLitre,
    transportFuelAvailableLitre: context.transportFuelAvailableLitre,
    transportFuelDeficitLitre: context.transportFuelDeficitLitre,
    transportDieselDemandLitre: context.transportDieselDemandLitre,
    transportDieselAvailableLitre: context.transportDieselAvailableLitre,
    transportDieselDeficitLitre: context.transportDieselDeficitLitre,
    transportElectricityDemandKwh: context.transportElectricityDemandKwh,
    transportFodderDemandKg: context.transportFodderDemandKg,
    transportFodderDeficitKg: context.transportFodderDeficitKg,
    transportLabourDemandDays: context.transportLabourDemandDays,
    unmetPassengerKm: context.unmetPassengerKm,
    unmetFreightTonneKm: context.unmetFreightTonneKm,
    totalPassengerKmDemand: context.totalPassengerKmDemand,
    totalFreightTonneKmDemand: context.totalFreightTonneKmDemand,
    localizedPassengerKmAvoided: context.localizedPassengerKmAvoided,
    localizedFreightTonneKmAvoided: context.localizedFreightTonneKmAvoided,
    dieselPassengerKm: context.dieselPassengerKm,
    dieselFreightTonneKm: context.dieselFreightTonneKm,
    nonDieselPassengerKm: context.nonDieselPassengerKm,
    nonDieselFreightTonneKm: context.nonDieselFreightTonneKm,
    railPassengerKm: context.railPassengerKm,
    railFreightTonneKm: context.railFreightTonneKm,
    railPassengerCapacityKm: context.railPassengerCapacityKm,
    railFreightCapacityTonneKm: context.railFreightCapacityTonneKm,
    passengerUtilizationRatio: context.passengerUtilizationRatio,
    freightUtilizationRatio: context.freightUtilizationRatio,
    weightedUtilizationRatio: context.weightedUtilizationRatio,
    railDieselDemandLitre: context.railDieselDemandLitre,
    railElectricityDemandKwh: context.railElectricityDemandKwh,
    railUnservedDemandDueToAccess: context.railUnservedDemandDueToAccess,
    railUnservedDemandDueToCondition: context.railUnservedDemandDueToCondition,
    railUtilizationRatio: context.railUtilizationRatio,
    railServiceReliability: context.railServiceReliability,
    railEnabled: context.railEnabled,
    railElectrified: context.railElectrified,
    railEligibleFoodFreightTonneKm: context.railEligibleFoodFreightTonneKm,
    railEligibleWoodFreightTonneKm: context.railEligibleWoodFreightTonneKm,
    railEligibleMaterialsFreightTonneKm: context.railEligibleMaterialsFreightTonneKm,
    railEligibleMarketFreightTonneKm: context.railEligibleMarketFreightTonneKm,
    railFreightCapturedTonneKm: context.railFreightCapturedTonneKm,
    totalFreightTonnes: context.totalFreightTonnes,
    essentialFreightTonneKm: context.essentialFreightTonneKm,
    localFreightTonneKm: context.localFreightTonneKm,
    longDistanceFreightTonneKm: context.longDistanceFreightTonneKm,
    avoidableFreightTonneKm: context.avoidableFreightTonneKm,
    freightDemandReducedByRepairReuse: context.freightDemandReducedByRepairReuse,
    freightDemandReducedByLocalProduction: context.freightDemandReducedByLocalProduction,
    freightDemandReducedByStorageProcessing: context.freightDemandReducedByStorageProcessing,
    freightDemandReducedByCompostLoop: context.freightDemandReducedByCompostLoop,
    roadFreightAvoidedTonneKm: context.roadFreightAvoidedTonneKm,
    freightDieselDemandLitre: context.freightDieselDemandLitre,
    freightElectricityDemandKwh: context.freightElectricityDemandKwh,
    freightHandlingLabourDays: context.freightHandlingLabourDays,
    freightSpoilageLossTonnes: context.freightSpoilageLossTonnes,
    freightServiceReliability: context.freightServiceReliability,
    catchmentPopulation: context.catchmentPopulation,
    catchmentHouseholds: context.catchmentHouseholds,
    catchmentJobs: context.catchmentJobs,
    catchmentServiceCapacity: context.catchmentServiceCapacity,
    catchmentFreightTonnePotential: context.catchmentFreightTonnePotential,
    catchmentProductiveLandHa: context.catchmentProductiveLandHa,
    catchmentWalkAccessShare: context.catchmentWalkAccessShare,
    catchmentBicycleAccessShare: context.catchmentBicycleAccessShare,
    householdsWithViableRailAlternative: context.householdsWithViableRailAlternative,
    householdsCarDependentNoAlternative: context.householdsCarDependentNoAlternative,
    stationAreaPopulationAdded: context.stationAreaPopulationAdded,
    stationAreaHousingUnitsAdded: context.stationAreaHousingUnitsAdded,
    stationAreaJobsAdded: context.stationAreaJobsAdded,
    stationAreaServiceCapacityAdded: context.stationAreaServiceCapacityAdded,
    stationAreaFreightPotentialAdded: context.stationAreaFreightPotentialAdded,
    hectaresTransitionedNearStations: context.hectaresTransitionedNearStations,
    roadMaintenanceDemandMoney: context.roadMaintenanceDemandMoney,
    roadMaintenanceBudgetMoney: context.roadMaintenanceBudgetMoney,
    roadMaintenanceBacklogMoney: context.roadMaintenanceBacklogMoney,
    roadMaintenanceCoverageRatio: context.roadMaintenanceCoverageRatio,
    roadConditionAverage: context.roadConditionAverage,
    roadConditionAverageByType: context.roadConditionAverageByType,
    roadMaintenanceDemandLabourDays: context.roadMaintenanceDemandLabourDays,
    roadMaintenanceDemandMaterialsKg: context.roadMaintenanceDemandMaterialsKg,
    railMaintenanceDemandMoney: context.railMaintenanceDemandMoney,
    railMaintenanceBudgetMoney: context.railMaintenanceBudgetMoney,
    railMaintenanceBacklogMoney: context.railMaintenanceBacklogMoney,
    railMaintenanceCoverageRatio: context.railMaintenanceCoverageRatio,
    railConditionAverage: context.railConditionAverage,
    railMaintenanceDemandLabourDays: context.railMaintenanceDemandLabourDays,
    railMaintenanceDemandMaterialsKg: context.railMaintenanceDemandMaterialsKg,
    roadCostPerPassengerKm: context.roadCostPerPassengerKm,
    roadCostPerTonneKm: context.roadCostPerTonneKm,
    railCostPerPassengerKm: context.railCostPerPassengerKm,
    railCostPerTonneKm: context.railCostPerTonneKm,
    avoidedRoadMaintenanceFromRailShift: context.avoidedRoadMaintenanceFromRailShift,
    heavyTruckTonneKmAvoidedByRail: context.heavyTruckTonneKmAvoidedByRail,
    heavyTruckTonneKm: context.heavyTruckTonneKm,
    vehicleKm: context.vehicleKm,
    privateIceCostPerKm: context.privateIceCostPerKm,
    publicTransitCostPerPassengerKm: context.publicTransitCostPerPassengerKm,
    railEconomicsCostPerPassengerKm: context.railEconomicsCostPerPassengerKm,
    railPassengerCostPerKmAtUtilization: context.railPassengerCostPerKmAtUtilization,
    railFreightCostPerTonneKmAtUtilization: context.railFreightCostPerTonneKmAtUtilization,
    railFixedCostAnnual: context.railFixedCostAnnual,
    railVariableCostAnnual: context.railVariableCostAnnual,
    railBreakEvenUtilizationRatio: context.railBreakEvenUtilizationRatio,
    railCostRecoveryRatio: context.railCostRecoveryRatio,
    railCostRecoveryRatioDirect: context.railCostRecoveryRatioDirect,
    railCostRecoveryRatioWithAvoidedCosts: context.railCostRecoveryRatioWithAvoidedCosts,
    railPublicSubsidyRequired: context.railPublicSubsidyRequired,
    railPassengerRevenueEquivalent: context.railPassengerRevenueEquivalent,
    railFreightRevenueEquivalent: context.railFreightRevenueEquivalent,
    railAvoidedRoadMaintenanceValue: context.railAvoidedRoadMaintenanceValue,
    railAvoidedDieselValue: context.railAvoidedDieselValue,
    railSpoilageReductionValue: context.railSpoilageReductionValue,
    railTotalBenefitEquivalent: context.railTotalBenefitEquivalent,
    railTotalCost: context.railTotalCost,
    railNetCostAfterBenefits: context.railNetCostAfterBenefits,
    railBenefitCostRatio: context.railBenefitCostRatio,
    railBreakEvenFreightTonneKm: context.railBreakEvenFreightTonneKm,
    railBreakEvenPassengerKm: context.railBreakEvenPassengerKm,
    railBreakEvenMixedUtilization: context.railBreakEvenMixedUtilization,
    railCostPerRiderYear: context.railCostPerRiderYear,
    annualFixedCost: context.annualFixedCost,
    annualVariableCost: context.annualVariableCost,
    directRevenuePerPassengerKm: context.directRevenuePerPassengerKm,
    directRevenuePerFreightTonneKm: context.directRevenuePerFreightTonneKm,
    avoidedCostPerPassengerKm: context.avoidedCostPerPassengerKm,
    avoidedCostPerFreightTonneKm: context.avoidedCostPerFreightTonneKm,
    effectiveBenefitPerPassengerKm: context.effectiveBenefitPerPassengerKm,
    effectiveBenefitPerFreightTonneKm: context.effectiveBenefitPerFreightTonneKm,
    requiredPassengerKmIfPassengerOnly: context.requiredPassengerKmIfPassengerOnly,
    requiredFreightTonneKmIfFreightOnly: context.requiredFreightTonneKmIfFreightOnly,
    requiredMixedUtilization: context.requiredMixedUtilization,
    currentPassengerKm: context.currentPassengerKm,
    currentFreightTonneKm: context.currentFreightTonneKm,
    passengerScaleMultiplierNeeded: context.passengerScaleMultiplierNeeded,
    freightScaleMultiplierNeeded: context.freightScaleMultiplierNeeded,
    mixedScaleMultiplierNeeded: context.mixedScaleMultiplierNeeded,
    sanityWarnings: context.sanityWarnings,
    warningCount: context.warningCount,
    criticalWarningCount: context.criticalWarningCount,
    calibrationProfile: context.calibrationProfile,
    scenarioScale: context.scenarioScale,
    fuelPriceInducedRailPassengerKm: context.fuelPriceInducedRailPassengerKm,
    fuelPriceInducedBusPassengerKm: context.fuelPriceInducedBusPassengerKm,
    privateVehicleCostBurdenWithAlternative: context.privateVehicleCostBurdenWithAlternative,
    privateVehicleCostBurdenWithoutAlternative: context.privateVehicleCostBurdenWithoutAlternative,
    gasolineBreakEvenPriceForTransitPerLitre: context.gasolineBreakEvenPriceForTransitPerLitre,
    dieselBreakEvenPriceForRailPerLitre: context.dieselBreakEvenPriceForRailPerLitre,
    householdAnnualPrivateVehicleCost: context.householdAnnualPrivateVehicleCost,
    householdAnnualTransitEquivalentCost: context.householdAnnualTransitEquivalentCost,
    averageCarDependenceCostBurden: context.averageCarDependenceCostBurden,
    electricityDemandKwh: context.electricityDemandKwh,
    electricityAvailableKwh: context.electricityAvailableKwh,
    electricityDeficitKwh: context.electricityDeficitKwh,
    biomassHarvestKg: context.biomassHarvestKg,
    sustainableBiomassHarvestKg: context.sustainableBiomassHarvestKg,
    fodderProducedKg: context.fodderProducedKg,
    fodderDemandKg: context.fodderDemandKg,
    fodderDeficitKg: context.fodderDeficitKg,
    fuelDeficitKg: context.fuelDeficitKg,
    localFoodCoverageRatio: context.localFoodCoverageRatio,
    foodDeficitPerPerson: context.foodDeficitPerPerson,
    averageFoodStress: context.averageFoodStress,
    averageFuelStress: context.averageFuelStress,
    averageHeatingFuelStress: context.averageHeatingFuelStress,
    averageTransportFuelStress: context.averageTransportFuelStress,
    averageElectricityStress: context.averageElectricityStress,
    averageTotalFuelStress: context.averageTotalFuelStress,
    averageHousingStress: context.averageHousingStress,
    averageTransportStress: context.averageTransportStress,
    averageTotalStress: context.averageTotalStress,
    averageMigrationPressure: context.averageMigrationPressure,
    averageHouseholdStress: context.averageHouseholdStress,
    averageCommuteCost: context.averageCommuteCost,
    averageFreightCost: context.averageFreightCost,
    rentPressure: context.rentPressure,
    averageRent: context.averageRent,
    baseAverageRent: context.baseAverageRent,
    averageAnnualHousingCost: context.averageAnnualHousingCost,
    averageHouseholdIncome: context.averageHouseholdIncome,
    averageHousingCostBurden: context.averageHousingCostBurden,
    householdsHousingStressed: context.householdsHousingStressed,
    householdsExceedingUnits: context.householdsExceedingUnits,
    households: context.households,
    dwellingUnits: context.dwellingUnits,
    occupiedUnits: context.occupiedUnits,
    vacantUnits: context.vacantUnits,
    valueToMonthlyRentRatio: context.valueToMonthlyRentRatio,
    priceToAnnualRentRatio: context.priceToAnnualRentRatio,
    valueToRentRatio: context.valueToRentRatio,
    averageRentGrowthRate: context.averageRentGrowthRate,
    housingVacancyRate: context.housingVacancyRate,
    averageEstimatedValue: context.averageEstimatedValue,
    averageEstimatedBuildingValue: context.averageEstimatedBuildingValue,
    populationTotal: context.populationTotal,
    populationUrban: context.populationUrban,
    populationRural: context.populationRural,
    startingPopulation: context.startingPopulation,
    births: context.births,
    deaths: context.deaths,
    inMigration: context.inMigration,
    outMigration: context.outMigration,
    netMigration: context.netMigration,
    urbanToRuralMoves: context.urbanToRuralMoves,
    ruralToUrbanMoves: context.ruralToUrbanMoves,
    endingPopulation: context.endingPopulation,
    outMigrationFoodStress: context.outMigrationFoodStress,
    outMigrationFuelStress: context.outMigrationFuelStress,
    outMigrationHousingStress: context.outMigrationHousingStress,
    outMigrationTransportStress: context.outMigrationTransportStress,
    infrastructureAverageCondition: context.infrastructureAverageCondition,
    soilCarbonAverage
  };

  for (const settlement of world.settlements) {
    const households = world.households.filter((household) => household.settlementId === settlement.id);
    const localFoodStress = average(households.map((household) => household.state.foodStress), 0.3);
    const localFuelStress = average(households.map((household) => household.state.fuelStress), 0.3);
    const localHeatingFuelStress = average(households.map((household) => household.state.heatingFuelStress), 0.3);
    const localTransportFuelStress = average(households.map((household) => household.state.transportFuelStress), 0.3);
    const localElectricityStress = average(households.map((household) => household.state.electricityStress), 0.3);
    const localTotalFuelStress = average(households.map((household) => household.state.totalFuelStress), 0.3);
    const localTransportStress = average(households.map((household) => household.state.transportStress), 0.3);
    const localHousingStress = average(households.map((household) => household.state.housingStress), 0.3);
    const localTotalStress = average(households.map((household) => household.state.totalStress), 0.3);
    const localMigrationPressure = average(households.map((household) => household.state.migrationPressure), 0.3);

    settlement.metrics = {
      ...settlement.metrics,
      year,
      households: households.length,
      averageFoodStress: localFoodStress,
      averageFuelStress: localFuelStress,
      averageHeatingFuelStress: localHeatingFuelStress,
      averageTransportFuelStress: localTransportFuelStress,
      averageElectricityStress: localElectricityStress,
      averageTotalFuelStress: localTotalFuelStress,
      averageHousingStress: localHousingStress,
      averageTransportStress: localTransportStress,
      averageTotalStress: localTotalStress,
      averageMigrationPressure: localMigrationPressure,
      walkableShare: settlement.metrics?.walkableShare ?? 0,
      localServiceCoverage: settlement.metrics?.localServiceCoverage ?? 0,
      villageServiceCoverage: settlement.metrics?.villageServiceCoverage ?? 0,
      railOrWaterFreightAccess: settlement.metrics?.railOrWaterFreightAccess ?? 0,
      marketGardenProximity: settlement.metrics?.marketGardenProximity ?? 0,
      averageTripDistanceKm: settlement.metrics?.averageTripDistanceKm ?? 0,
      percentAvailableLabourDemandedByFood: context.percentAvailableLabourDemandedByFood,
      percentAvailableLabourSuppliedToFood: context.percentAvailableLabourSuppliedToFood,
      percentTotalLabourDemandFromFood: context.percentTotalLabourDemandFromFood,
      foodLabourDemandDays: context.foodLabourDemandDays,
      foodLabourSuppliedDays: context.foodLabourSuppliedDays,
      foodLabourUnmetDays: context.foodLabourUnmetDays,
      localFoodCoverageRatio: context.localFoodCoverageRatio,
      ruralOpportunity: (1 - localFoodStress) * 0.35
        + (1 - localTransportStress) * 0.25
        + (1 - localHousingStress) * 0.15
        + (settlement.socialCohesion * 0.15)
        + (settlement.institutionalTrust * 0.1)
    };
  }

  return regionalMetrics;
}
