import test from 'node:test';
import assert from 'node:assert/strict';
import {buildCarryingCapacityPresentationContract} from '../src/presentation.mjs';

test('public presentation contains perennial evidence, reference-only candidates and metric display units', () => {
  const contract = buildCarryingCapacityPresentationContract({generatedAt: 'test'});
  assert.equal(contract.metric_only_presentation, true);
  assert.equal(contract.contract_version, '3.0.0');
  assert.equal(contract.agroecosystem.plant_database_version, '1.0.0');
  assert.ok(contract.agroecosystem.reference_plan.whole_diet.years.length >= 30);
  assert.equal(contract.agroecosystem.reference_plan.reconciliation.unknown_values_are_not_zero, true);
  assert.deepEqual(contract.units, {energy: 'MJ/day and GJ/year', land: 'ha', labour: 'hours/year', population: 'people'});
  assert.equal(contract.reference_profile.sex, 'male');
  assert.equal(contract.reference_profile.weight_kg, 75);
  assert.equal(contract.reference_profile.height_cm, 178);
  assert.equal(contract.environment.climate.growing_degree_days.value_degree_days, 2073.5);
  assert.equal(contract.environment.solar.status, 'unresolved');
  assert.equal(contract.nutrition.contract_version, '1.4.0');
  assert.equal(contract.livestock.contract_version, '1.10.0');
  assert.equal(contract.nutrition.days_per_year, 365.25);
  assert.ok(contract.nutrition.goals.minimum_property_b12);
  assert.ok(contract.nutrition.food_portfolio.some((row) => row.id === 'carrot_raw'));
  assert.ok(contract.nutrition.food_portfolio.every((row) => row.food_gj_ha_year > 0 && row.production_type));
  assert.equal(contract.livestock.labour_scaling.method, 'task_based_species_specific_planning_model');
  assert.match(contract.livestock.labour_scaling.formula, /processing setup/);
  assert.match(contract.livestock.labour_scaling.note, /unsupported fixed\/variable percentage/i);
  assert.ok(contract.livestock.labour_scaling.task_definitions.rabbit_meat.sensitivities.low);
  const familyRabbit = contract.livestock.examples['two_adults_plus_three_children:ordinary_mesic'].rows.find((row) => row.mode === 'rabbit_meat' && row.ration_id === 'arc_integrated');
  assert.equal(familyRabbit.livestock_system_count, 1);
  assert.equal(familyRabbit.animals[0].reproduction.breeding_females, 4);
  assert.equal(familyRabbit.animals[0].reproduction.breeding_males, 1);
  assert.equal(familyRabbit.animals[0].reproduction.kits_surviving_year, 84);
  assert.equal(familyRabbit.animals[0].output.edible_meat_kg_year, 40.8);
  assert.equal(familyRabbit.animals[0].labour.scaling_method, contract.livestock.labour_scaling.method);
  assert.equal(familyRabbit.animals[0].labour.recurring_hours_year, 180);
  assert.equal(familyRabbit.animals[0].labour.slaughter_processing_hours_year, 45);
  assert.equal(familyRabbit.nutrient_completeness.demand.aggregate.annual.b12, 3506.4);
  assert.equal(familyRabbit.nutrient_completeness.nutrients.b12.target_daily, 9.6);
  assert.equal(familyRabbit.nutrient_completeness.nutrients.b12.target_annual, 3506.4);
  assert.equal(contract.nutrition.food_composition_source.includes('open.canada.ca'), true);
  assert.equal(contract.public_arc_contract.publication_ready, true);
  assert.equal(contract.public_arc_contract.contract_version, '1.1.0');
  assert.equal(contract.public_arc_contract.canonical_household, 'two_adults_plus_three_children');
  assert.equal(contract.livestock.species.chicken_eggs.canonical_arc, true);
  assert.equal(contract.livestock.species.chicken_meat.canonical_arc, false);
  assert.equal(contract.establishment.starting_condition, 'bare_land_new_planting');
  assert.ok(contract.establishment.site_models.ordinary_mesic.perennial_mix.length > 0);
  assert.ok(contract.transition_rows.some((row) => Number(row.establishment_land_requirement_ha) > Number(row.mature_land_requirement_ha)));
  assert.equal(contract.perennial_food_evidence.rows.length, 8);
  assert.ok(contract.perennial_food_evidence.rows.some((row) => row.species === 'Heartnut/Japanese walnut' && row.evidence_status === 'reference only' && row.mature_food_gj_ha_year === null));
  assert.ok(contract.perennial_food_evidence.rows.some((row) => row.species === 'White oak/acorn systems' && row.evidence_status === 'reference only'));
  assert.equal(contract.perennial_food_evidence.mix_timeline.at(-1).harvested_food_gj_year, contract.perennial_food_evidence.central_mix.mature_food_gj_ha_year);
  assert.equal(contract.heating.default_building.archetype, 'arc_yurt');
  assert.ok(contract.heating.insulation_presets.good.wall_rsi > 0);
  const publicJson = JSON.stringify(contract);
  assert.equal(/\bkcal\b/i.test(publicJson), false);
  assert.equal(/\bcalories?\b/i.test(publicJson), false);
  assert.equal(/"(?:wall|roof|floor)_r"\s*:/.test(publicJson), false);
  assert.deepEqual(contract.site_lease_economics.adult_scale.scenarios.map((row) => row.adult_residents), [1, 4, 12, 16, 20, 22, 24, 28, 40, 56]);
  const adultScale = contract.site_lease_economics.adult_scale;
  const row24 = adultScale.scenarios.find((row) => row.adult_residents === 24);
  assert.equal(row24.households, 12);
  assert.equal(row24.dependent_children_capacity, 36);
  assert.equal(row24.total_parcel_hectares, 34.665556);
  assert.equal(adultScale.land_market.improved_property_observation_count, 7);
  assert.equal(adultScale.land_market.usable_arc_acquisition_observation_count, 36);
  assert.equal(row24.acquisition_economics.vacant_land.land_price_cad_per_ha, 21288.13);
  assert.equal(row24.acquisition_economics.arc_usable_acquisition.land_price_cad_per_ha, 21288.13);
  assert.equal(contract.site_lease_economics.adult_scale.family_capacity_standard.household_profile_id, 'two_adults_plus_three_children');
  assert.equal(contract.site_lease_economics.adult_scale.land_market.local_parcel_curve_status, 'partial_measured_whole_property_curve');
  assert.ok(contract.site_lease_economics.adult_scale.land_market.usable_whole_property_observation_count >= 30);
  assert.ok(contract.site_lease_economics.adult_scale.land_market.productive_land_comparators.some((row) => row.observation_id === 'grey-2024-tillable-benchmark'));
  const crossover = contract.site_lease_economics.adult_scale.economic_crossover;
  assert.deepEqual(crossover.scan_adult_counts, [1, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56]);
  assert.equal(crossover.first_evidence_backed_band_crossover.adult_residents, 2);
  assert.equal(crossover.market_band_crossover.adult_residents, 14);
  assert.equal(crossover.first_over_20_ha.adult_residents, 14);
  assert.equal(crossover.first_over_20_ha.households, 7);
  assert.equal(crossover.farm_scale_entry_adults, 14);
  assert.equal(crossover.diminishing_savings_point_adults, 14);
  assert.equal(crossover.economic_sweet_spot.next_adult_residents, 16);
  assert.ok(crossover.market_band_crossings.some((row) => row.adult_residents === 14 && row.previous_land_band === '10–20 ha' && row.new_land_band === '20–40 ha'));
  const acquisitionCrossover = contract.site_lease_economics.adult_scale.economic_crossover_by_market.arc_usable_acquisition;
  assert.equal(acquisitionCrossover.first_over_20_ha.adult_residents, 14);
  assert.equal(acquisitionCrossover.market_band_crossover.adult_residents, 14);
  assert.equal(acquisitionCrossover.economic_sweet_spot.next_adult_residents, 16);
  assert.equal(acquisitionCrossover.market_band_crossings.find((row) => row.adult_residents === 28).new_land_band, '40+ ha');
  assert.equal(acquisitionCrossover.market_band_crossings.find((row) => row.adult_residents === 28).evidence_sufficient_for_new_band, true);
  assert.equal(contract.site_lease_economics.adult_scale.economic_crossover_by_market.improved_property.market_band_crossover.status, 'unresolved');
  assert.ok(contract.site_lease_economics.adult_scale.land_market.sources.some((source) => source.institution.includes('Ontario Farmland')));
});
