import {calculateHealthCanadaEER, representativeProfiles} from './health-canada.mjs';

const round = (value, digits = 6) => Math.round(Number(value) * 10 ** digits) / 10 ** digits;
export const siteClasses = {wetter_productive: {label: 'Wetter productive site', food_multiplier: 1, woody_band: 'favourable', notes: 'Moisture-tolerant woody systems can be considered, but exceptional saturated-site trials are excluded.'}, ordinary_mesic: {label: 'Ordinary mesic site', food_multiplier: 1, woody_band: 'ordinary', notes: 'Central planning class for reasonably designed mixed perennial and annual production.'}, dry: {label: 'Dry site', food_multiplier: .75, woody_band: 'marginal', notes: 'Water limitation is represented as a transparent scenario multiplier, not a measured Grey County average.'}, shallow_rocky_marginal: {label: 'Shallow/rocky marginal site', food_multiplier: .5, woody_band: 'marginal', notes: 'Lower productivity scenario; a site survey is required before using it for a parcel.'}};
export const householdProfiles = {one_adult: {label: '1 adult', member_ids: ['adult_woman'], adult_count: 1}, adult_plus_child: {label: '1 adult + 1 child', member_ids: ['adult_woman', 'child_girl_8'], adult_count: 1}, two_adults: {label: '2 adults', member_ids: ['adult_woman', 'adult_man'], adult_count: 2}, two_adults_plus_one_child: {label: '2 adults + 1 child', member_ids: ['adult_woman', 'adult_man', 'child_girl_8'], adult_count: 2}, two_adults_plus_two_children: {label: '2 adults + 2 children', member_ids: ['adult_woman', 'adult_man', 'child_girl_8', 'adolescent_boy_14'], adult_count: 2}, two_adults_plus_three_children: {label: '2 adults + 3 children', member_ids: ['adult_woman', 'adult_man', 'child_girl_8', 'adolescent_boy_14', 'child_boy_8'], adult_count: 2}};
export const arcPolicyAdultAllocationHa = 1;
export const policySiteMap = {favourable: 'wetter_productive', ordinary: 'ordinary_mesic', marginal: 'shallow_rocky_marginal'};
export const foodLossAssumptions = {storage_loss: .1, wildlife_loss: .1, seed_propagation_loss: .03, weather_crop_reserve: .2, emergency_community_reserve: .1};
export const FOOD_ADULT_EQUIVALENT_GJ_YEAR = (calculateHealthCanadaEER(representativeProfiles.adult_woman).gj_year + calculateHealthCanadaEER(representativeProfiles.adult_man).gj_year) / 2;
export const heatingCases = {low: {diameter_m: 9.1, floor_area_m2: 65.6, wall_height_m: 2.4, roof_rise_m: 2, wall_r: 25, roof_r: 45, floor_r: 35, window_area_m2: 6, window_u: .25, ach: .20, indoor_c: 20, design_c: -20, hdd: 4031.9, net_factor: .75, thermal_bridge: 1.10, heater_efficiency: .85, cord_gj: 8}, central: {diameter_m: 9.1, floor_area_m2: 65.6, wall_height_m: 2.4, roof_rise_m: 2, wall_r: 20, roof_r: 40, floor_r: 30, window_area_m2: 8, window_u: .30, ach: .35, indoor_c: 20, design_c: -20, hdd: 4031.9, net_factor: .85, thermal_bridge: 1.15, heater_efficiency: .75, cord_gj: 10}, high: {diameter_m: 9.1, floor_area_m2: 65.6, wall_height_m: 2.4, roof_rise_m: 2, wall_r: 15, roof_r: 30, floor_r: 20, window_area_m2: 10, window_u: .40, ach: .60, indoor_c: 20, design_c: -20, hdd: 4031.9, net_factor: .95, thermal_bridge: 1.30, heater_efficiency: .65, cord_gj: 12}};

export function calculateEvidenceHeating(overrides = {}) {
  const a = {...heatingCases.central, ...overrides}; const radius = a.diameter_m / 2; const circumference = Math.PI * a.diameter_m; const wallGross = circumference * a.wall_height_m; const roofSlope = Math.sqrt(radius ** 2 + a.roof_rise_m ** 2); const roofArea = Math.PI * radius * roofSlope; const wallOpaque = wallGross - a.window_area_m2; const volume = Math.PI * radius ** 2 * a.wall_height_m + Math.PI * radius ** 2 * a.roof_rise_m / 3; const rToRsi = .1761101838; const wallU = 1 / (a.wall_r * rToRsi); const roofU = 1 / (a.roof_r * rToRsi); const floorU = 1 / (a.floor_r * rToRsi); const opaqueUa = (wallOpaque * wallU + roofArea * roofU + a.floor_area_m2 * floorU) * a.thermal_bridge; const windowUa = a.window_area_m2 * a.window_u; const ventilationUa = .33 * a.ach * volume; const totalUa = opaqueUa + windowUa + ventilationUa; const grossEnvelopeGJ = totalUa * a.hdd * 24 / 1000 * .0036; const usefulGJ = grossEnvelopeGJ * a.net_factor; const grossWoodGJ = usefulGJ / a.heater_efficiency;
  return {assumptions: a, geometry: {radius_m: round(radius, 4), wall_gross_m2: round(wallGross, 4), wall_opaque_m2: round(wallOpaque, 4), roof_area_m2: round(roofArea, 4), floor_area_m2: a.floor_area_m2, conditioned_volume_m3: round(volume, 4)}, heat_loss: {wall_u_w_m2k: round(wallU, 6), roof_u_w_m2k: round(roofU, 6), floor_u_w_m2k: round(floorU, 6), opaque_ua_w_k: round(opaqueUa, 6), window_ua_w_k: round(windowUa, 6), ventilation_ua_w_k: round(ventilationUa, 6), total_ua_w_k: round(totalUa, 6), annual_gross_envelope_loss_gj: round(grossEnvelopeGJ, 6), annual_useful_space_heating_gj: round(usefulGJ, 6), design_heat_loss_kw: round(totalUa * (a.indoor_c - a.design_c) / 1000, 6)}, wood: {gross_wood_energy_required_gj: round(grossWoodGJ, 6), heater_efficiency: a.heater_efficiency, dry_wood_energy_gj_per_tonne: 19, approximate_dry_wood_tonnes: round(grossWoodGJ / 19, 6), approximate_dry_wood_kg: round(grossWoodGJ / 19 * 1000, 2), cord_energy_gj: a.cord_gj, approximate_cords_per_year: round(grossWoodGJ / a.cord_gj, 6)}};
}

export function calculateFoodSystem(foodEvidence, demandGJ, siteMultiplier = 1, proteinReferenceWeightKg = 70) {
  const wanted = {potato_low_input_synthesis: .25, wheat_low_input_synthesis: .2, dry_beans_low_input_synthesis: .2, sunflower_low_input_synthesis: .25, oats_low_input_synthesis: .1};
  const rows = Object.entries(wanted).map(([id, energyShare]) => { const row = foodEvidence.rows.find((item) => item.id === id); if (!row || !row.food_gj_ha) throw new Error(`Missing canonical food-system row: ${id}`); const foodGJHa = row.food_gj_ha * siteMultiplier; return {id, crop: row.crop, category: row.category, energy_share: energyShare, food_gj_ha: foodGJHa, area_ha: demandGJ * energyShare / foodGJHa, protein_kg_ha: row.protein_kg_ha * siteMultiplier, fat_kg_ha: row.fat_kg_ha * siteMultiplier, carbohydrate_kg_ha: row.carbohydrate_kg_ha * siteMultiplier}; });
  const rawArea = rows.reduce((sum, row) => sum + row.area_ha, 0); const grossEnergyPerHa = demandGJ / rawArea; const postHarvestFactor = (1 - foodLossAssumptions.storage_loss) * (1 - foodLossAssumptions.wildlife_loss) * (1 - foodLossAssumptions.seed_propagation_loss); const householdDeliveryFactor = postHarvestFactor * (1 - foodLossAssumptions.weather_crop_reserve - foodLossAssumptions.emergency_community_reserve); const requiredArea = demandGJ / (grossEnergyPerHa * householdDeliveryFactor);
  const macro = rows.reduce((totals, row) => { const area = requiredArea * row.area_ha / rawArea; totals.protein_kg += area * row.protein_kg_ha; totals.fat_kg += area * row.fat_kg_ha; totals.carbohydrate_kg += area * row.carbohydrate_kg_ha; return totals; }, {protein_kg: 0, fat_kg: 0, carbohydrate_kg: 0});
  const deliveredMacro = Object.fromEntries(Object.entries(macro).map(([key, value]) => [key, value * householdDeliveryFactor])); const macroEnergyGJ = {protein: deliveredMacro.protein_kg * .016736, fat: deliveredMacro.fat_kg * .037656, carbohydrate: deliveredMacro.carbohydrate_kg * .016736}; const macroEnergyTotal = Object.values(macroEnergyGJ).reduce((sum, value) => sum + value, 0); const macroShares = Object.fromEntries(Object.entries(macroEnergyGJ).map(([key, value]) => [key, round(value / macroEnergyTotal * 100, 3)]));
  return {diet_energy_shares: wanted, rows, gross_energy_per_ha: round(grossEnergyPerHa), raw_calorie_area_ha: round(rawArea), delivery_factor_after_losses_and_reserves: round(householdDeliveryFactor), required_food_area_ha: round(requiredArea), gross_food_energy_at_required_area_gj: round(grossEnergyPerHa * requiredArea), delivered_food_energy_gj: round(grossEnergyPerHa * requiredArea * householdDeliveryFactor), macro_output_at_required_area: Object.fromEntries(Object.entries(macro).map(([key, value]) => [key, round(value)])), macro_delivered_to_household: Object.fromEntries(Object.entries(deliveredMacro).map(([key, value]) => [key, round(value)])), macro_energy_shares_percent: macroShares, protein_g_day: round(deliveredMacro.protein_kg * 1000 / 365.25, 3), protein_reference_target_g_day: round(proteinReferenceWeightKg * .8, 3), protein_threshold_met: deliveredMacro.protein_kg * 1000 / 365.25 >= proteinReferenceWeightKg * .8, macro_range_check: {protein_10_to_35_percent: macroShares.protein >= 10 && macroShares.protein <= 35, fat_20_to_35_percent: macroShares.fat >= 20 && macroShares.fat <= 35, carbohydrate_45_to_65_percent: macroShares.carbohydrate >= 45 && macroShares.carbohydrate <= 65, status: 'screening check only; does not establish micronutrient sufficiency'}, assumptions: {...foodLossAssumptions, protein_reference_g_per_kg: .8, macro_energy_factors: '4 kcal/g protein and carbohydrate; 9 kcal/g fat converted to GJ'}};
}

export function calculateInteractiveHousehold({members, siteId = 'ordinary_mesic', foodEvidence, woodyCases, matureReferenceRow} = {}) {
  const demand = members.reduce((sum, member) => sum + Number(member.gj_year), 0); const referenceWeight = members.reduce((sum, member) => sum + Number(member.weight_kg), 0); const site = siteClasses[siteId] ?? siteClasses.ordinary_mesic; const food = calculateFoodSystem(foodEvidence, demand, site.food_multiplier, referenceWeight); const heatingArea = woodyCases.central[site.woody_band].required_woody_area_ha; const resilience = {diversity_and_rotation_ha: round(Math.max(.12, food.required_food_area_ha * .25)), soil_water_perennial_buffer_ha: .15, fibre_habitat_wildlife_buffer_ha: .1}; const robustMinimum = food.required_food_area_ha + heatingArea + resilience.diversity_and_rotation_ha; const referenceDemand = Number(matureReferenceRow?.household_food_gj_year ?? demand) || demand;
  return {members, household_food_gj_year: round(demand), food_adult_equivalents: round(demand / FOOD_ADULT_EQUIVALENT_GJ_YEAR), food_adult_equivalent_basis_gj_year: round(FOOD_ADULT_EQUIVALENT_GJ_YEAR), food_area_ha: food.required_food_area_ha, heating_area_ha: round(heatingArea), resilience_allowances_ha: resilience, robust_minimum_area_ha: round(robustMinimum), reference_transition_scale: round(demand / referenceDemand), site_id: siteId, caveat: 'Food-adult-equivalent is a food-energy normalization only, not a total-land multiplier. Custom-household transition rows scale the canonical reference transition by Health Canada food energy; preset household rows use the full canonical transition output.'};
}
