import {calculateHouseholdProteinDemand} from './protein.mjs';
import {calculateFoodNutrientAdequacy, FOOD_NUTRIENT_PROFILES} from './nutrition.mjs';
import {FOOD_ADULT_EQUIVALENT_GJ_YEAR} from './food-adult-equivalent.mjs';

const round = (value, digits = 6) => Math.round(Number(value) * 10 ** digits) / 10 ** digits;

export const LIVESTOCK_CONTRACT_VERSION = '1.6.0';

// The reference livestock system is sized for the canonical two-adult plus
// three-dependent-child planning household. Other households resize the
// animals inside that system; they do not receive several complete colonies.
export const CANONICAL_HOUSEHOLD_FAE = 4.29;
export const LIVESTOCK_SCALING_BASIS = 'household_food_adult_equivalents_divided_by_canonical_household_fae';

const SOURCE = {
  rabbit: 'https://files.ontario.ca/omafra-starting-farm-in-ontario-pub-61-en-2023-04-21.pdf; https://extension.usu.edu/washington/files/Understanding_the_Basics_of_Rabbit_Care.pdf',
  poultry: 'https://www.ontario.ca/page/introduction-poultry-nutrition; https://extension.umn.edu/small-scale-poultry/raising-chickens-eggs',
  goose: 'https://extension.psu.edu/poultry-nutrition-and-feeding; https://extension.psu.edu/geese-ducks-and-swans',
  goat: 'https://files.ontario.ca/omafra-pasture-production-en-2022-12-08.pdf; https://www.gov.mb.ca/agriculture/livestock/goat/pubs/goats-and-their-nutrition.pdf',
  composition: 'https://open.canada.ca/data/en/dataset/1b6139bd-ed7e-4043-bc28-ff00e10f3109',
  chickenBreeds: 'https://afs.mgcafe.uky.edu/research/poultry/use-heritage-breeds-alternative-poultry-production; https://extension.umd.edu/sites/extension.umd.edu/files/publications/FS-987%20Choosing%20the%20Best%20Poultry%20Breeds%20for%20your%20Small%20Farm_0.pdf; https://pmc.ncbi.nlm.nih.gov/articles/PMC8858978/'
};

/**
 * Feed streams are deliberately separate from crop hectares. A zero land
 * requirement means the stream is a by-product, browse or overlay already
 * generated by the modeled property; it is not unlimited free feed.
 */
export const LIVESTOCK_FEED_STREAMS = {
  human_food_grade: {label: 'Human-food-grade crop', class: 'human_food_grade', dry_matter_energy_mj_kg: 15, protein_fraction: .18, human_edible_fraction: 1, winter_storage: true, storage_loss_fraction: .10, land_required: true, dedicated_feed_dm_yield_kg_ha: 2500, evidence_status: 'derived_food_system_input; local feed-crop planning synthesis', source: SOURCE.composition},
  human_edible_surplus: {label: 'Human-edible surplus', class: 'human_edible_surplus', dry_matter_energy_mj_kg: 14, protein_fraction: .16, human_edible_fraction: 1, winter_storage: true, storage_loss_fraction: .10, land_required: false, local_replacement_stream: 'human_food_grade', evidence_status: 'derived_after_human_food_priority', source: SOURCE.composition},
  crop_byproduct: {label: 'Crop by-product', class: 'crop_byproduct', dry_matter_energy_mj_kg: 10, protein_fraction: .10, human_edible_fraction: .15, winter_storage: true, storage_loss_fraction: .12, land_required: false, local_replacement_stream: 'human_food_grade', evidence_status: 'planning_synthesis', source: SOURCE.composition},
  garden_cull: {label: 'Garden cull', class: 'garden_cull', dry_matter_energy_mj_kg: 11, protein_fraction: .12, human_edible_fraction: .30, winter_storage: false, storage_loss_fraction: .20, land_required: false, local_replacement_stream: 'human_food_grade', evidence_status: 'planning_synthesis', source: SOURCE.composition},
  herbaceous_forage: {label: 'Herbaceous forage', class: 'herbaceous_forage', dry_matter_energy_mj_kg: 9, protein_fraction: .12, human_edible_fraction: 0, winter_storage: true, storage_loss_fraction: .15, land_required: true, dedicated_feed_dm_yield_kg_ha: 4000, evidence_status: 'extension_bounded_planning_synthesis', source: 'https://extension.psu.edu/average-nutrient-composition-of-typical-high-quality-pastures-dry-matter-basis'},
  pasture: {label: 'Pasture', class: 'pasture', dry_matter_energy_mj_kg: 9.5, protein_fraction: .15, human_edible_fraction: 0, winter_storage: false, storage_loss_fraction: .20, land_required: true, dedicated_feed_dm_yield_kg_ha: 2500, evidence_status: 'extension_bounded_planning_synthesis', source: 'https://extension.psu.edu/average-nutrient-composition-of-typical-high-quality-pastures-dry-matter-basis'},
  hay: {label: 'Stored hay', class: 'hay', dry_matter_energy_mj_kg: 8.5, protein_fraction: .10, human_edible_fraction: 0, winter_storage: true, storage_loss_fraction: .15, land_required: true, dedicated_feed_dm_yield_kg_ha: 3500, evidence_status: 'extension_bounded_planning_synthesis', source: 'https://www.ontario.ca/page/pasture-production'},
  leaf_fodder: {label: 'Food-forest leaf fodder', class: 'leaf_fodder', dry_matter_energy_mj_kg: 8, protein_fraction: .12, human_edible_fraction: 0, winter_storage: true, storage_loss_fraction: .20, land_required: true, dedicated_feed_dm_yield_kg_ha: 1000, evidence_status: 'planning_synthesis_requires_site_inventory', source: SOURCE.goat},
  woody_browse: {label: 'Woody browse', class: 'woody_browse', dry_matter_energy_mj_kg: 7.5, protein_fraction: .10, human_edible_fraction: 0, winter_storage: true, storage_loss_fraction: .25, land_required: true, dedicated_feed_dm_yield_kg_ha: 1500, evidence_status: 'extension_bounded_planning_synthesis_requires_browse_inventory', source: SOURCE.goat},
  food_forest_understorey: {label: 'Food-forest understorey', class: 'food_forest_understorey', dry_matter_energy_mj_kg: 8.5, protein_fraction: .12, human_edible_fraction: 0, winter_storage: true, storage_loss_fraction: .18, land_required: true, dedicated_feed_dm_yield_kg_ha: 1500, evidence_status: 'planning_synthesis_requires_site_inventory', source: SOURCE.goat},
  invertebrate: {label: 'Invertebrates', class: 'invertebrate', dry_matter_energy_mj_kg: 12, protein_fraction: .45, human_edible_fraction: .05, winter_storage: false, storage_loss_fraction: .25, land_required: false, local_replacement_stream: 'human_food_grade', evidence_status: 'planning_synthesis', source: SOURCE.poultry},
  purchased_concentrate: {label: 'Purchased concentrate', class: 'purchased_concentrate', dry_matter_energy_mj_kg: 12, protein_fraction: .18, human_edible_fraction: .90, winter_storage: true, storage_loss_fraction: .05, land_required: false, evidence_status: 'external_input_reference', source: SOURCE.poultry},
  mineral_supplement: {label: 'Mineral supplement', class: 'mineral_supplement', dry_matter_energy_mj_kg: 0, protein_fraction: 0, human_edible_fraction: 1, winter_storage: true, storage_loss_fraction: 0, land_required: false, evidence_status: 'health_requirement_not_food_energy', source: SOURCE.poultry}
};

export const CHICKEN_BREED_CANDIDATES = {
  chantecler: {label: 'Chantecler', true_breeding: true, cold_hardiness: 'high', natural_reproduction: 'possible; flock-specific broodiness', range_foraging: 'moderate; local validation required', forage_behaviour: 'outdoor forage contribution is plausible but not quantified here', locomotion: 'mobile enough for outdoor ranging; flock-specific validation required', heat_tolerance: 'not quantified; Grey County cold hardiness is the relevant reference condition', growth_rate: 'slow-growing dual-purpose reference; not a broiler performance claim', feed_requirement: 'bounded flock synthesis; lower-concentration assumption than industrial broiler', longevity: 'multi-season breeding flock assumed', dual_purpose: true, canonical_reference: true, evidence_status: 'qualitative breed/reference evidence; quantitative flock values are planning synthesis', source: SOURCE.chickenBreeds},
  plymouth_rock: {label: 'Plymouth Rock', true_breeding: true, cold_hardiness: 'moderate-high', natural_reproduction: 'possible; flock-specific broodiness', range_foraging: 'moderate', forage_behaviour: 'outdoor-range candidate; no local intake estimate', locomotion: 'outdoor-range candidate', heat_tolerance: 'not separately modelled', growth_rate: 'slow/dual-purpose relative to industrial broilers', feed_requirement: 'planning comparison only', longevity: 'not separately modelled', dual_purpose: true, canonical_reference: false, evidence_status: 'comparison candidate', source: SOURCE.chickenBreeds},
  rhode_island_red: {label: 'Rhode Island Red', true_breeding: true, cold_hardiness: 'moderate-high', natural_reproduction: 'possible; flock-specific broodiness', range_foraging: 'moderate', forage_behaviour: 'outdoor-range candidate; no local intake estimate', locomotion: 'outdoor-range candidate', heat_tolerance: 'not separately modelled', growth_rate: 'slow/dual-purpose relative to industrial broilers', feed_requirement: 'planning comparison only', longevity: 'not separately modelled', dual_purpose: true, canonical_reference: false, evidence_status: 'comparison candidate', source: SOURCE.chickenBreeds},
  sussex: {label: 'Sussex', true_breeding: true, cold_hardiness: 'moderate', natural_reproduction: 'possible; flock-specific broodiness', range_foraging: 'good', forage_behaviour: 'good outdoor-range candidate; no local intake estimate', locomotion: 'good outdoor-range candidate', heat_tolerance: 'not separately modelled', growth_rate: 'slow/dual-purpose relative to industrial broilers', feed_requirement: 'planning comparison only', longevity: 'not separately modelled', dual_purpose: true, canonical_reference: false, evidence_status: 'comparison candidate', source: SOURCE.chickenBreeds}
};

export const CHICKEN_SYSTEM_COMPARISON = {
  canonical: {label: 'Self-replacing true-breeding dual-purpose flock', breeding: 'natural mating with retained replacement birds; no recurring chicks or pullets', locomotion_and_range: 'outdoor mobility, range use and forage behaviour are relevant; intake contribution remains bounded and site-specific', heat_tolerance: 'not a Grey County selection driver and not quantitatively modelled', growth_and_feed: 'slow-growing/dual-purpose planning boundary; no commercial broiler feed-conversion or carcass assumptions are inherited', climate: 'cold-hardy reference range for Grey County, with Chantecler selected as the conservative reference', sources: SOURCE.chickenBreeds, evidence_status: 'breed comparison and flock outputs are planning synthesis; local flock validation required'},
  industrial_sensitivity: {label: 'Fast-growing commercial broiler sensitivity', breeding: 'recurring production-bird replacement; excluded from canonical ARC carrying capacity', locomotion_and_range: 'selection for rapid growth can reduce mobility/range suitability relative to slower-growing birds', heat_tolerance: 'comparative heat/locomotion evidence is context-specific and not transferred into the canonical flock', growth_and_feed: 'commercial performance is a separate sensitivity and must not be used for the canonical flock', climate: 'not selected as the Grey County self-replacing reference', sources: SOURCE.chickenBreeds, evidence_status: 'non-canonical comparison boundary'}
};

const species = {
  rabbit_meat: {
    id: 'rabbit_meat', label: 'Self-replacing rabbits', animal: 'Rabbit', unit_label: 'Breeding does/buck plus household fryer output', output: {edible_meat_kg_year: 40.8, food_energy_gj_year: .232, edible_protein_kg_year: 8.89, edible_fat_kg_year: 1.43}, feed_dm_kg_year: 350, winter_fraction: .60, housing_area_m2: 12, fencing_m: 25, water_l_day: 35, labour_hours_year: 180, physical_labour: 'moderate-high', slaughter_processing_hours_year: 45, manure_kg_year: 300, production_start_year: 1, food_profile_id: 'rabbit_meat_raw', reproduction: {breeding_does: 4, breeding_bucks: 1, litters_year: 4, kits_per_litter: 7, kit_survival: .75, replacement_does_year: 1, replacement_bucks_year: .25, external_replacement_animals_year: 0, feed_all_generations_included: true, self_replacing: true, evidence_status: 'bounded smallholder planning synthesis'}, sources: [SOURCE.rabbit], canonical_arc: true, notes: 'Breeding stock, replacements and fryer output are included in the self-replacing household rabbitry. Forage and leaves are bounded supplements rather than an assumption of grass-only production.'
  },
  chicken_eggs: {
    id: 'chicken_eggs', label: 'Self-replacing dual-purpose chicken flock', animal: 'Chicken', unit_label: '8 breeding hens plus 1 breeding rooster; integrated eggs and surplus-bird meat', output: {eggs_kg_year: 68.65, eggs_year: 1373, edible_meat_kg_year: 11.66, food_energy_gj_year: 1.04, edible_protein_kg_year: 11.3, edible_fat_kg_year: 8.6}, feed_dm_kg_year: 700, winter_fraction: .55, housing_area_m2: 10, fencing_m: 35, water_l_day: 5, labour_hours_year: 210, physical_labour: 'moderate', slaughter_processing_hours_year: 35, manure_kg_year: 420, production_start_year: 1, food_profile_id: 'chicken_egg_raw', food_profile_id_by_output: {eggs: 'chicken_egg_raw', meat: 'chicken_meat_raw'}, reproduction: {breeding_hens: 8, breeding_roosters: 1, eggs_per_hen_year: 180, incubation_eggs_year: 24, hatch_rate: .80, juvenile_survival: .85, female_chick_fraction: .5, replacement_hens_year: 4, replacement_roosters_year: 1, egg_loss_fraction: .03, egg_mass_kg: .05, surplus_cockerel_edible_meat_kg: 1, cull_hen_edible_meat_kg: 1, cull_rooster_edible_meat_kg: .8, external_replacement_chicks_year: 0, external_replacement_pullets_year: 0, feed_all_generations_included: true, reference_breed: 'Chantecler / conservative true-breeding dual-purpose range', reproduction_modes: ['broody_hen', 'local_incubator'], reproduction_mode_note: 'Broody hens avoid incubator electricity but reduce edible eggs; a locally powered incubator trades electricity and labour for more controlled hatch timing.', genetic_resilience_note: 'Occasional unrelated breeding-stock introduction may be prudent, but it is not an annual production input.', evidence_status: 'planning synthesis; breed and reproduction figures require local flock validation'}, sources: [SOURCE.poultry, SOURCE.chickenBreeds], canonical_arc: true, notes: 'Canonical chicken is an integrated, naturally mating, true-breeding dual-purpose flock. Gross eggs are reduced for incubation and losses; meat comes from surplus cockerels and cull birds. Feed includes breeding adults and growing replacements.'
  },
  chicken_meat: {
    id: 'chicken_meat', label: 'Fast-growing meat chicken sensitivity', animal: 'Chicken', unit_label: '25 recurring meat birds per year', output: {edible_meat_kg_year: 35, food_energy_gj_year: .42, edible_protein_kg_year: 7.0, edible_fat_kg_year: 5.6}, feed_dm_kg_year: 125, winter_fraction: .25, housing_area_m2: 8, fencing_m: 25, water_l_day: 12, labour_hours_year: 150, physical_labour: 'moderate', slaughter_processing_hours_year: 60, manure_kg_year: 180, production_start_year: 1, food_profile_id: 'chicken_meat_raw', reproduction: {external_replacement_chicks_year: 25, external_replacement_pullets_year: 0, feed_all_generations_included: false, self_replacing: false, evidence_status: 'non-canonical industrial/specialist sensitivity'}, sources: [SOURCE.poultry], canonical_arc: false, notes: 'Non-canonical sensitivity only. It assumes recurring production birds and cannot qualify as ARC self-replacing carrying capacity.'
  },
  goose_meat: {
    id: 'goose_meat', label: 'Self-replacing grazing-biased geese', animal: 'Goose', unit_label: 'Breeding geese plus surplus gosling meat', output: {edible_meat_kg_year: 24, food_energy_gj_year: .34, edible_protein_kg_year: 5.0, edible_fat_kg_year: 3.8}, feed_dm_kg_year: 1050, winter_fraction: .35, housing_area_m2: 10, fencing_m: 45, water_l_day: 16, labour_hours_year: 160, physical_labour: 'moderate', slaughter_processing_hours_year: 36, manure_kg_year: 850, production_start_year: 1, food_profile_id: 'goose_meat_raw', reproduction: {breeding_females: 3, breeding_males: 1, fertile_eggs_year: 24, hatch_rate: .75, gosling_survival: .80, replacement_females_year: 1, replacement_males_year: .25, external_replacement_animals_year: 0, feed_all_generations_included: true, self_replacing: true, evidence_status: 'bounded smallholder planning synthesis'}, sources: [SOURCE.goose], canonical_arc: true, notes: 'Pasture contribution is substantial but seasonal; breeding adults, replacement birds, winter feed, shelter and water are included.'
  },
  goat_meat: {
    id: 'goat_meat', label: 'Self-replacing browse-biased goats', animal: 'Goat', unit_label: 'Breeding does/buck plus annual meat-kid output', output: {edible_meat_kg_year: 30, food_energy_gj_year: .43, edible_protein_kg_year: 6.0, edible_fat_kg_year: 4.5}, feed_dm_kg_year: 1200, winter_fraction: .55, housing_area_m2: 14, fencing_m: 120, water_l_day: 12, labour_hours_year: 260, physical_labour: 'high', slaughter_processing_hours_year: 50, manure_kg_year: 950, production_start_year: 2, food_profile_id: null, reproduction: {breeding_does: 2, breeding_bucks: .25, kids_year: 3, kid_survival: .85, replacement_does_year: .5, replacement_bucks_year: .1, external_replacement_animals_year: 0, feed_all_generations_included: true, self_replacing: true, evidence_status: 'bounded smallholder planning synthesis; goat food composition profile unresolved'}, sources: [SOURCE.goat], canonical_arc: true, notes: 'Goats can browse a large share of their diet, but browse inventory, fencing, hay and winter supplementation are site-specific. A matching CNF goat-meat food form remains unresolved for micronutrient accounting.'
  }
};

export const LIVESTOCK_SPECIES = species;

// These are discrete minimum viable production units, not fractional nutrient
// knobs. A smaller scale may be useful for a sensitivity calculation, but it
// cannot represent a self-replacing ARC population.
export const MINIMUM_SELF_REPLACING_SYSTEMS = {
  rabbit_meat: {minimum_scale: 1, label: 'Minimum self-replacing rabbit colony', breeding_does: 4, breeding_bucks: 1},
  chicken_eggs: {minimum_scale: 1, label: 'Minimum self-replacing dual-purpose chicken flock', breeding_hens: 8, breeding_roosters: 1},
  goose_meat: {minimum_scale: 1, label: 'Minimum self-replacing goose flock', breeding_females: 3, breeding_males: 1},
  goat_meat: {minimum_scale: 1, label: 'Minimum self-replacing goat herd', breeding_does: 2, breeding_bucks: .25}
};

const whole = (value) => Math.max(0, Math.round(Number(value)));
const activeWhole = (value, scale) => Number(scale) > 0 ? Math.max(1, whole(value)) : 0;

export function deriveLivestockScale({foodDemandGJYear, livestockMode = 'plants_only', livestockScale} = {}) {
  if (livestockMode === 'plants_only') return 0;
  if (livestockScale !== undefined && livestockScale !== null) return Math.max(0, Number(livestockScale));
  const foodAdultEquivalents = Number(foodDemandGJYear ?? 0) / FOOD_ADULT_EQUIVALENT_GJ_YEAR;
  return Math.max(0, foodAdultEquivalents / CANONICAL_HOUSEHOLD_FAE);
}

// Kept as a compatibility export. It now reports selected system bases, not
// a number of complete systems generated by household size.
export function deriveLivestockSystemCount({livestockMode = 'plants_only'} = {}) {
  if (livestockMode === 'plants_only') return 0;
  return livestockMode === 'mixed_rabbit_eggs' ? 2 : 1;
}

function livestockPopulation(speciesId, scale = 1) {
  const factor = Math.max(0, Number(scale));
  const active = factor > 0;
  const reproduction = LIVESTOCK_SPECIES[speciesId]?.reproduction ?? {};
  if (speciesId === 'rabbit_meat') {
    const baseDoes = Number(reproduction.breeding_does ?? 4);
    const littersPerDoe = Number(reproduction.litters_year ?? 4);
    const kitsPerLitter = Number(reproduction.kits_per_litter ?? 7);
    const breedingFemales = activeWhole(baseDoes * factor, factor);
    const breedingMales = active ? Math.max(1, Math.ceil(breedingFemales / 8)) : 0;
    const litters = breedingFemales * littersPerDoe;
    const kitsBorn = litters * kitsPerLitter;
    const kitsSurviving = whole(kitsBorn * Number(reproduction.kit_survival ?? .75));
    const replacementFemales = active ? Math.max(1, whole(Number(reproduction.replacement_does_year ?? 1) * breedingFemales / baseDoes)) : 0;
    const replacementMales = active ? Number(reproduction.replacement_bucks_year ?? .25) * (breedingFemales / baseDoes) : 0;
    const harvestable = Math.max(0, kitsSurviving - replacementFemales - replacementMales);
    const canonicalHarvestable = 84 - 1 - .25;
    return {breeding_females: breedingFemales, breeding_males: breedingMales, litters_year: litters, kits_born_year: kitsBorn, kits_surviving_year: kitsSurviving, replacement_females_year: replacementFemales, replacement_males_year: replacementMales, animals_available_for_harvest_year: harvestable, feed_scale: breedingFemales / baseDoes, output_scale: harvestable / canonicalHarvestable, housing_scale: (breedingFemales + breedingMales) / 5, buck_capacity_does: 8, buck_capacity_note: 'One breeding buck is retained through eight does before an additional buck is planned.'};
  }
  if (speciesId === 'chicken_eggs') {
    const baseHens = Number(reproduction.breeding_hens ?? 8);
    const breedingFemales = activeWhole(baseHens * factor, factor);
    const breedingMales = active ? Math.max(1, Math.ceil(breedingFemales / 8)) : 0;
    const incubationEggs = active ? Math.max(1, whole(Number(reproduction.incubation_eggs_year ?? 24) * breedingFemales / baseHens)) : 0;
    const chicks = incubationEggs * Number(reproduction.hatch_rate ?? .80) * Number(reproduction.juvenile_survival ?? .85);
    const females = chicks * Number(reproduction.female_chick_fraction ?? .5);
    const males = chicks * (1 - Number(reproduction.female_chick_fraction ?? .5));
    const replacementFemales = active ? Math.max(1, whole(Number(reproduction.replacement_hens_year ?? 4) * breedingFemales / baseHens)) : 0;
    const replacementMales = active ? Math.max(1, whole(Number(reproduction.replacement_roosters_year ?? 1) * breedingMales)) : 0;
    const surplusMales = Math.max(0, males - replacementMales);
    const surplusFemales = Math.max(0, females - replacementFemales);
    const grossEggs = breedingFemales * Number(reproduction.eggs_per_hen_year ?? 180);
    const edibleEggs = Math.max(0, (grossEggs - incubationEggs) * (1 - Number(reproduction.egg_loss_fraction ?? .03)));
    const edibleMeat = surplusMales * Number(reproduction.surplus_cockerel_edible_meat_kg ?? 1) + surplusFemales * Number(reproduction.cull_hen_edible_meat_kg ?? 1) + replacementMales * Number(reproduction.cull_rooster_edible_meat_kg ?? .8);
    return {breeding_females: breedingFemales, breeding_males: breedingMales, fertile_eggs_year: incubationEggs, eggs_incubated_year: incubationEggs, chicks_hatched_and_surviving_year: chicks, replacement_females_year: replacementFemales, replacement_males_year: replacementMales, surplus_males_year: surplusMales, surplus_females_year: surplusFemales, gross_eggs_year: grossEggs, edible_eggs_year: edibleEggs, edible_eggs_kg_year: edibleEggs * Number(reproduction.egg_mass_kg ?? .05), edible_meat_kg_year: edibleMeat, feed_scale: breedingFemales / baseHens, output_scale: breedingFemales / baseHens, housing_scale: (breedingFemales + breedingMales) / 9, rooster_capacity_hens: 8, rooster_capacity_note: 'One breeding rooster is retained through eight hens before an additional rooster is planned.'};
  }
  if (speciesId === 'goose_meat') {
    const baseFemales = Number(reproduction.breeding_females ?? 3);
    const breedingFemales = activeWhole(baseFemales * factor, factor);
    const breedingMales = active ? Math.max(1, Math.ceil(breedingFemales / 3)) : 0;
    const fertileEggs = breedingFemales * Number(reproduction.fertile_eggs_year ?? 24) / baseFemales;
    const goslings = fertileEggs * Number(reproduction.hatch_rate ?? .75) * Number(reproduction.gosling_survival ?? .80);
    const replacementFemales = active ? Math.max(1, whole(Number(reproduction.replacement_females_year ?? 1) * breedingFemales / baseFemales)) : 0;
    const replacementMales = active ? Number(reproduction.replacement_males_year ?? .25) * (breedingFemales / baseFemales) : 0;
    const harvestable = Math.max(0, goslings - replacementFemales - replacementMales);
    const canonicalHarvestable = 14.4 - 1 - .25;
    return {breeding_females: breedingFemales, breeding_males: breedingMales, fertile_eggs_year: fertileEggs, goslings_hatched_and_surviving_year: goslings, replacement_females_year: replacementFemales, replacement_males_year: replacementMales, animals_available_for_harvest_year: harvestable, feed_scale: breedingFemales / baseFemales, output_scale: harvestable / canonicalHarvestable, housing_scale: (breedingFemales + breedingMales) / 4, gander_capacity_females: 3, gander_capacity_note: 'One breeding male is retained through three females before an additional male is planned.'};
  }
  if (speciesId === 'goat_meat') {
    const baseFemales = Number(reproduction.breeding_does ?? 2);
    const breedingFemales = activeWhole(baseFemales * factor, factor);
    const breedingMales = active ? Math.max(1, Math.ceil(breedingFemales / 8)) : 0;
    const kidsBorn = breedingFemales * Number(reproduction.kids_year ?? 3) / baseFemales;
    const kidsSurviving = kidsBorn * Number(reproduction.kid_survival ?? .85);
    const replacementFemales = active ? Math.max(1, whole(Number(reproduction.replacement_does_year ?? .5) * breedingFemales / baseFemales)) : 0;
    const replacementMales = active ? Number(reproduction.replacement_bucks_year ?? .1) * (breedingFemales / baseFemales) : 0;
    const harvestable = Math.max(0, kidsSurviving - replacementFemales - replacementMales);
    const canonicalHarvestable = 2.55 - 1 - .1;
    return {breeding_females: breedingFemales, breeding_males: breedingMales, kids_born_year: kidsBorn, kids_surviving_year: kidsSurviving, replacement_females_year: replacementFemales, replacement_males_year: replacementMales, animals_available_for_harvest_year: harvestable, feed_scale: breedingFemales / baseFemales, output_scale: harvestable / canonicalHarvestable, housing_scale: (breedingFemales + breedingMales) / 3, buck_capacity_does: 8, buck_capacity_note: 'One breeding buck is retained through eight does before an additional buck is planned.'};
  }
  if (speciesId === 'chicken_meat') {
    const productionAnimals = activeWhole(25 * factor, factor);
    return {production_animals_year: productionAnimals, feed_scale: productionAnimals / 25, output_scale: productionAnimals / 25, housing_scale: productionAnimals / 25};
  }
  return {feed_scale: factor, output_scale: factor, housing_scale: factor};
}

export function calculateLivestockReproductiveLedger({speciesId, scale = 1} = {}) {
  const animal = LIVESTOCK_SPECIES[speciesId];
  const reproduction = animal?.reproduction;
  if (!animal || !reproduction) return {self_replacing: false, external_replacement_animals_year: null, feed_all_generations_included: false, status: 'reproduction ledger unavailable'};
  const population = livestockPopulation(speciesId, scale);
  const external = Number(reproduction.external_replacement_animals_year ?? reproduction.external_replacement_chicks_year ?? 0) * Number(scale);
  if (speciesId === 'chicken_eggs') {
    return {self_replacing: true, external_replacement_chicks_year: 0, external_replacement_pullets_year: 0, feed_all_generations_included: true, ...population, gross_eggs_year: population.gross_eggs_year, edible_eggs_year: population.edible_eggs_year, edible_eggs_kg_year: population.edible_eggs_kg_year, edible_meat_kg_year: population.edible_meat_kg_year, output: {eggs_year: population.edible_eggs_year, eggs_kg_year: population.edible_eggs_kg_year, edible_meat_kg_year: population.edible_meat_kg_year}, reference_breed: reproduction.reference_breed, evidence_status: reproduction.evidence_status};
  }
  return {self_replacing: reproduction.self_replacing !== false && external === 0, external_replacement_animals_year: external, feed_all_generations_included: reproduction.feed_all_generations_included === true, ...population, evidence_status: reproduction.evidence_status};
}

export const LIVESTOCK_RATION_SCENARIOS = {
  conventional_reference: {
    id: 'conventional_reference', label: 'External-feed sensitivity (non-ARC)', description: 'Normal smallholder reference ration with external feed; shown only as a sensitivity and excluded from canonical ARC optimization.', allow_purchased_feed: true, canonical_arc: false,
    shares: {rabbit_meat: {purchased_concentrate: .60, hay: .25, crop_byproduct: .10, herbaceous_forage: .05}, chicken_eggs: {purchased_concentrate: .80, human_food_grade: .10, garden_cull: .10}, chicken_meat: {purchased_concentrate: .80, crop_byproduct: .10, garden_cull: .10}, goose_meat: {pasture: .35, herbaceous_forage: .25, hay: .15, purchased_concentrate: .25}, goat_meat: {hay: .45, woody_browse: .30, purchased_concentrate: .25}}
  },
  low_food_competition: {
    id: 'low_food_competition', label: 'Low-food-competition sensitivity (non-ARC)', description: 'Maximizes forage, browse, culls and residues while retaining external supplements; not ARC feed self-sufficiency compliant.', allow_purchased_feed: true, canonical_arc: false,
    shares: {rabbit_meat: {herbaceous_forage: .35, leaf_fodder: .20, hay: .20, crop_byproduct: .15, purchased_concentrate: .10}, chicken_eggs: {garden_cull: .25, invertebrate: .10, crop_byproduct: .15, human_edible_surplus: .10, purchased_concentrate: .40}, chicken_meat: {garden_cull: .20, invertebrate: .10, crop_byproduct: .20, human_edible_surplus: .10, purchased_concentrate: .40}, goose_meat: {pasture: .45, herbaceous_forage: .20, hay: .15, crop_byproduct: .10, purchased_concentrate: .10}, goat_meat: {woody_browse: .55, leaf_fodder: .20, hay: .15, purchased_concentrate: .10}}
  },
  arc_integrated: {
    id: 'arc_integrated', label: 'ARC on-site feed', description: 'All dietary feed energy and protein is produced on the ARC property through finite co-products and dedicated feed hectares. Purchased feed is prohibited.', allow_purchased_feed: false, canonical_arc: true,
    shares: {rabbit_meat: {herbaceous_forage: .25, leaf_fodder: .20, crop_byproduct: .15, food_forest_understorey: .15, hay: .25}, chicken_eggs: {garden_cull: .25, invertebrate: .15, crop_byproduct: .15, human_edible_surplus: .10, human_food_grade: .35}, chicken_meat: {garden_cull: .20, invertebrate: .15, crop_byproduct: .20, human_edible_surplus: .10, human_food_grade: .35}, goose_meat: {pasture: .45, herbaceous_forage: .25, crop_byproduct: .10, hay: .20}, goat_meat: {woody_browse: .55, leaf_fodder: .20, hay: .25}}
  }
};

export const PROPERTY_FEED_SUPPLY_RULES = {
  crop_byproduct_kg_dm_per_ha_annual_food: 250,
  garden_cull_kg_dm_per_ha_annual_food: 80,
  food_forest_understorey_kg_dm_per_ha_perennial_food: 180,
  leaf_fodder_kg_dm_per_ha_perennial_food: 80,
  woody_browse_kg_dm_per_ha_perennial_food: 120,
  herbaceous_forage_kg_dm_per_ha_perennial_food: 160,
  pasture_kg_dm_per_ha: 0,
  invertebrate_kg_dm_per_ha_food_area: 30,
  status: 'explicit planning synthesis; requires a property biomass inventory before operational use',
  double_counting_rule: 'These are finite co-products/overlays within the modeled food areas. Dedicated feed hectares are added for any shortfall; the same stream is not assigned twice.'
};

function normalizedShares(shares = {}) {
  const total = Object.values(shares).reduce((sum, value) => sum + Number(value), 0);
  if (!(total > 0)) throw new Error('livestock ration must contain a positive feed share');
  return Object.fromEntries(Object.entries(shares).map(([id, value]) => [id, Number(value) / total]));
}

export function derivePropertyFeedSupply({foodSystem = {}} = {}) {
  const foodArea = Number(foodSystem.required_food_area_ha ?? 0);
  const annualArea = foodArea * .25;
  const perennialArea = foodArea * .75;
  const rules = PROPERTY_FEED_SUPPLY_RULES;
  return {
    crop_byproduct: annualArea * rules.crop_byproduct_kg_dm_per_ha_annual_food,
    garden_cull: foodArea * rules.garden_cull_kg_dm_per_ha_annual_food,
    food_forest_understorey: perennialArea * rules.food_forest_understorey_kg_dm_per_ha_perennial_food,
    leaf_fodder: perennialArea * rules.leaf_fodder_kg_dm_per_ha_perennial_food,
    woody_browse: perennialArea * rules.woody_browse_kg_dm_per_ha_perennial_food,
    herbaceous_forage: perennialArea * rules.herbaceous_forage_kg_dm_per_ha_perennial_food,
    pasture: 0,
    invertebrate: foodArea * rules.invertebrate_kg_dm_per_ha_food_area,
    human_edible_surplus: 0,
    source: rules.status,
    food_area_basis_ha: foodArea,
    double_counting_rule: rules.double_counting_rule
  };
}

export function calculateFeedLedger({speciesId, rationId = 'arc_integrated', scale = 1, propertyFeedSupply = {}, siteCapability = {}, requireSelfSufficient = null} = {}) {
  const animal = LIVESTOCK_SPECIES[speciesId];
  const ration = LIVESTOCK_RATION_SCENARIOS[rationId] ?? LIVESTOCK_RATION_SCENARIOS.arc_integrated;
  if (!animal) throw new Error(`Unknown livestock species: ${speciesId}`);
  const shares = normalizedShares(ration.shares[speciesId]);
  const totalDm = Number(animal.feed_dm_kg_year) * Number(scale);
  const selfSufficient = requireSelfSufficient ?? !ration.allow_purchased_feed;
  const feedYieldMultiplier = Math.max(0, Number(siteCapability.feed_yield_multiplier ?? siteCapability.food_yield_multiplier ?? 1));
  const rows = Object.entries(shares).map(([streamId, share]) => {
    const stream = LIVESTOCK_FEED_STREAMS[streamId];
    if (!stream) throw new Error(`Unknown feed stream: ${streamId}`);
    const required = totalDm * share;
    const available = Math.max(0, Number(propertyFeedSupply[streamId] ?? 0));
    const onProperty = Math.min(required, available);
    const unmet = Math.max(0, required - onProperty);
    const producerId = stream.dedicated_feed_dm_yield_kg_ha > 0 ? streamId : stream.local_replacement_stream;
    const producer = producerId ? LIVESTOCK_FEED_STREAMS[producerId] : null;
    const producerYield = Number(producer?.dedicated_feed_dm_yield_kg_ha ?? 0) * feedYieldMultiplier;
    const localProductionPossible = selfSufficient && unmet > 0 && producer && producerYield > 0;
    const dedicatedConsumed = localProductionPossible ? unmet : 0;
    const storageFactor = stream.winter_storage ? Math.max(.01, 1 - Number(producer?.storage_loss_fraction ?? stream.storage_loss_fraction ?? 0)) : 1;
    const dedicatedProduction = localProductionPossible ? dedicatedConsumed / storageFactor : 0;
    const dedicatedLand = localProductionPossible ? dedicatedProduction / producerYield : 0;
    const purchased = !selfSufficient ? unmet : 0;
    const unresolved = selfSufficient ? (localProductionPossible ? 0 : unmet) : 0;
    const components = [{dm: onProperty, source: stream}, {dm: dedicatedConsumed, source: producer}, {dm: purchased, source: stream}].filter((component) => component.source && component.dm > 0);
    const actual = (field, fallback = 0) => components.reduce((sum, component) => sum + component.dm * Number(component.source?.[field] ?? fallback), 0);
    return {stream_id: streamId, stream_label: stream.label, class: stream.class, required_dm_kg: round(required), on_property_dm_kg: round(onProperty), dedicated_feed_dm_kg: round(dedicatedProduction), dedicated_feed_land_ha: round(dedicatedLand), dedicated_consumed_dm_kg: round(dedicatedConsumed), local_production_stream_id: localProductionPossible ? producerId : null, purchased_dm_kg: round(purchased), unresolved_feed_deficit_dm_kg: round(unresolved), total_feed_energy_gj: round(actual('dry_matter_energy_mj_kg') / 1000), total_feed_protein_kg: round(actual('protein_fraction')), human_edible_feed_dm_kg: round(actual('human_edible_fraction')), human_edible_feed_protein_kg: round(components.reduce((sum, component) => sum + component.dm * Number(component.source?.protein_fraction ?? 0) * Number(component.source?.human_edible_fraction ?? 0), 0)), on_property_human_edible_feed_protein_kg: round(onProperty * stream.protein_fraction * stream.human_edible_fraction), property_grown_dedicated_human_edible_feed_protein_kg: round(dedicatedConsumed * Number(producer?.protein_fraction ?? 0) * Number(producer?.human_edible_fraction ?? 0)), winter_stored_dm_kg: stream.winter_storage ? round(required) : 0, winter_stored_dm_available_kg: stream.winter_storage ? round(onProperty + dedicatedConsumed + purchased) : 0, storage_loss_dm_kg: round(Math.max(0, dedicatedProduction - dedicatedConsumed)), human_edible_fraction: stream.human_edible_fraction, evidence_status: stream.evidence_status, source: stream.source};
  });
  const required = rows.reduce((sum, row) => sum + row.required_dm_kg, 0);
  const property = rows.reduce((sum, row) => sum + row.on_property_dm_kg, 0);
  const dedicatedProduction = rows.reduce((sum, row) => sum + row.dedicated_feed_dm_kg, 0);
  const dedicatedLand = rows.reduce((sum, row) => sum + row.dedicated_feed_land_ha, 0);
  const purchased = rows.reduce((sum, row) => sum + row.purchased_dm_kg, 0);
  const winter = rows.reduce((sum, row) => sum + row.winter_stored_dm_kg, 0);
  const winterAvailable = rows.reduce((sum, row) => sum + row.winter_stored_dm_available_kg, 0);
  const unresolved = rows.reduce((sum, row) => sum + row.unresolved_feed_deficit_dm_kg, 0);
  return {
    species_id: speciesId,
    ration_id: ration.id,
    rows,
    dry_matter_requirement_kg_year: round(required),
    on_property_dry_matter_kg_year: round(property),
    purchased_dry_matter_kg_year: round(purchased),
    property_grown_dedicated_feed_dm_kg_year: round(dedicatedProduction),
    additional_dedicated_feed_land_ha: round(dedicatedLand),
    feed_deficit_dm_kg_year: round(unresolved),
    human_edible_feed_dm_kg_year: round(rows.reduce((sum, row) => sum + row.human_edible_feed_dm_kg, 0)),
    human_inedible_feed_dm_kg_year: round(rows.reduce((sum, row) => sum + row.required_dm_kg - row.human_edible_feed_dm_kg, 0)),
    feed_protein_kg_year: round(rows.reduce((sum, row) => sum + row.total_feed_protein_kg, 0)),
    human_edible_feed_protein_kg_year: round(rows.reduce((sum, row) => sum + row.human_edible_feed_protein_kg, 0)),
    on_property_human_edible_feed_protein_kg_year: round(rows.reduce((sum, row) => sum + row.on_property_human_edible_feed_protein_kg, 0)),
    winter_stored_feed_required_kg_year: round(winter),
    winter_stored_feed_available_kg_year: round(winterAvailable),
    winter_feed_deficit_kg_year: round(Math.max(0, winter - winterAvailable)),
    storage_loss_kg_year: round(rows.reduce((sum, row) => sum + row.storage_loss_dm_kg, 0)),
    purchased_feed_required: purchased > 0,
    feed_self_sufficiency: unresolved === 0 && purchased === 0 && winterAvailable >= winter,
    feed_energy_import_gj_year: round(rows.reduce((sum, row) => sum + row.purchased_dm_kg * (LIVESTOCK_FEED_STREAMS[row.stream_id]?.dry_matter_energy_mj_kg ?? 0) / 1000, 0)),
    source: animal.sources,
    ration_description: ration.description
  };
}

export function calculateLivestockScenario({speciesId, rationId = 'arc_integrated', scale = 1, propertyFeedSupply = {}, siteCapability = {}, requireSelfSufficient = null} = {}) {
  const animal = LIVESTOCK_SPECIES[speciesId];
  const population = livestockPopulation(speciesId, scale);
  const feed = calculateFeedLedger({speciesId, rationId, scale: population.feed_scale ?? scale, propertyFeedSupply, siteCapability, requireSelfSufficient});
  const outputScale = Number(population.output_scale ?? scale);
  const reproduction = calculateLivestockReproductiveLedger({speciesId, scale});
  const output = {...Object.fromEntries(Object.entries(animal.output).map(([key, value]) => [key, round(Number(value) * outputScale)])), ...(reproduction.output ?? {})};
  const outputProfiles = animal.food_profile_id_by_output ?? {};
  const profileProtein = (profileId, kg) => Number(FOOD_NUTRIENT_PROFILES[profileId]?.protein_g_per_100g ?? 0) * Number(kg ?? 0) / 100;
  const edibleProtein = Object.keys(outputProfiles).length
    ? Object.entries(outputProfiles).reduce((sum, [product, profileId]) => sum + profileProtein(profileId, product === 'eggs' ? output.eggs_kg_year : output.edible_meat_kg_year), 0)
    : Number(animal.output.edible_protein_kg_year) * outputScale;
  if (Object.keys(outputProfiles).length) output.edible_protein_kg_year = round(edibleProtein);
  return {
    species_id: speciesId,
    label: animal.label,
    animal: animal.animal,
    unit_label: animal.unit_label,
    scale: Number(scale),
    livestock_scale: Number(scale),
    population,
    output,
    food_profile_id: animal.food_profile_id ?? null,
    food_profile_id_by_output: animal.food_profile_id_by_output ?? null,
    reproduction,
    feed,
    net_human_edible_protein_kg_year: round(edibleProtein - feed.human_edible_feed_protein_kg_year),
    human_edible_protein_conversion_efficiency: feed.human_edible_feed_protein_kg_year > 0 ? round(edibleProtein / feed.human_edible_feed_protein_kg_year, 4) : null,
    human_inedible_feed_fraction: feed.dry_matter_requirement_kg_year > 0 ? round(feed.human_inedible_feed_dm_kg_year / feed.dry_matter_requirement_kg_year) : 0,
    housing: {area_m2: round(animal.housing_area_m2 * Number(population.housing_scale ?? outputScale)), fencing_m: round(animal.fencing_m * Number(population.housing_scale ?? outputScale)), water_l_day: round(animal.water_l_day * Number(population.housing_scale ?? outputScale))},
    labour: (() => {
      // Fixed/variable splits are planning assumptions where no species study
      // reports household-scale labour directly. They preserve the canonical
      // reference total while avoiding four copies of setup work.
      const labourSplits = {rabbit_meat: {recurring_fixed: 60, recurring_variable: 120, processing_variable: 45}, chicken_eggs: {recurring_fixed: 70, recurring_variable: 140, processing_variable: 35}, chicken_meat: {recurring_fixed: 50, recurring_variable: 100, processing_variable: 60}, goose_meat: {recurring_fixed: 60, recurring_variable: 100, processing_variable: 36}, goat_meat: {recurring_fixed: 100, recurring_variable: 160, processing_variable: 50}};
      const split = labourSplits[speciesId] ?? {recurring_fixed: 0, recurring_variable: animal.labour_hours_year, processing_variable: animal.slaughter_processing_hours_year};
      const recurringScale = Number(scale) > 0 ? Number(population.feed_scale ?? outputScale) : 0;
      const processingScale = Number(population.output_scale ?? outputScale);
      const recurringFixed = split.recurring_fixed * (Number(scale) > 0 ? 1 : 0);
      const recurringVariable = split.recurring_variable * recurringScale;
      const processing = split.processing_variable * processingScale;
      return {recurring_fixed_hours_year: round(recurringFixed), recurring_variable_hours_year: round(recurringVariable), recurring_hours_year: round(recurringFixed + recurringVariable), slaughter_processing_hours_year: round(processing), total_hours_year: round(recurringFixed + recurringVariable + processing), physical_intensity: animal.physical_labour, scaling_note: 'Fixed setup/care work is counted once per selected system; animal-dependent care and processing scale from the actual population.'};
    })(),
    manure_kg_year: round(animal.manure_kg_year * Number(population.feed_scale ?? outputScale)),
    production_start_year: animal.production_start_year,
    source: animal.sources,
    evidence_status: 'planning_synthesis_bounded_by_extension_and_government_guidance',
    notes: animal.notes
  };
}

export function calculateMinimumSelfReplacingLivestockSystem({speciesId = 'rabbit_meat', rationId = 'arc_integrated', propertyFeedSupply = {}, siteCapability = {}} = {}) {
  const definition = MINIMUM_SELF_REPLACING_SYSTEMS[speciesId];
  if (!definition) throw new Error(`No minimum self-replacing system is defined for ${speciesId}`);
  return calculateLivestockScenario({speciesId, rationId, scale: definition.minimum_scale, propertyFeedSupply, siteCapability, requireSelfSufficient: true});
}

export function calculateNutrientFoodSystem({foodEvidence, demandGJ, proteinDemandKgYear, members = [], siteCapability, livestockMode = 'plants_only', rationId = 'arc_integrated', livestockScale, establishmentYears = [1, 2, 3, 5, 8, 10, 15, 'mature']} = {}) {
  if (!foodEvidence) throw new Error('nutrient food system requires canonical food evidence');
  const {calculateFoodSystem} = siteCapability?.calculateFoodSystem ? siteCapability : {};
  if (typeof calculateFoodSystem !== 'function') throw new Error('nutrient food system requires calculateFoodSystem in siteCapability');
  const plantOnly = calculateFoodSystem(foodEvidence, demandGJ, siteCapability);
  const proteinTarget = Number(proteinDemandKgYear ?? 0);
  const modes = livestockMode === 'plants_only' ? [] : livestockMode === 'mixed_rabbit_eggs' ? ['rabbit_meat', 'chicken_eggs'] : [livestockMode];
  const effectiveLivestockScale = deriveLivestockScale({foodDemandGJYear: demandGJ, livestockMode, livestockScale});
  const livestockSystemCount = deriveLivestockSystemCount({livestockMode});
  const livestockScalingBasis = livestockMode === 'plants_only'
    ? 'plants_only_zero_systems'
    : livestockScale !== undefined && livestockScale !== null
      ? 'explicit_sensitivity_override'
      : LIVESTOCK_SCALING_BASIS;
  const animalOutputs = modes.map((speciesId) => calculateLivestockScenario({speciesId, rationId, scale: effectiveLivestockScale, propertyFeedSupply: {}, siteCapability}));
  const animalEnergy = animalOutputs.reduce((sum, row) => sum + Number(row.output.food_energy_gj_year ?? 0), 0);
  const animalProtein = animalOutputs.reduce((sum, row) => sum + Number(row.output.edible_protein_kg_year ?? 0), 0);
  const plantDemandGJ = Math.max(0, Number(demandGJ) - animalEnergy);
  const plantFood = plantDemandGJ === Number(demandGJ) ? plantOnly : calculateFoodSystem(foodEvidence, plantDemandGJ, siteCapability);
  const plantProtein = Number(plantFood.macro_delivered_to_household?.protein_kg ?? 0);
  const totalProtein = plantProtein + animalProtein;
  const deficit = Math.max(0, proteinTarget - totalProtein);
  const propertyFeed = derivePropertyFeedSupply({foodSystem: plantFood});
  const remainingPropertyFeed = {...propertyFeed};
  const animals = animalOutputs.map((row) => {
    const result = calculateLivestockScenario({speciesId: row.species_id, rationId, scale: row.scale, propertyFeedSupply: remainingPropertyFeed, siteCapability});
    for (const feedRow of result.feed.rows) remainingPropertyFeed[feedRow.stream_id] = Math.max(0, Number(remainingPropertyFeed[feedRow.stream_id] ?? 0) - Number(feedRow.on_property_dm_kg ?? 0));
    return result;
  });
  const annualFeed = animals.reduce((sum, row) => sum + row.feed.dry_matter_requirement_kg_year, 0);
  const winterFeed = animals.reduce((sum, row) => sum + row.feed.winter_stored_feed_required_kg_year, 0);
  const purchasedFeed = animals.reduce((sum, row) => sum + row.feed.purchased_dry_matter_kg_year, 0);
  const dedicatedFeedLand = animals.reduce((sum, row) => sum + row.feed.additional_dedicated_feed_land_ha, 0);
  const feedDeficit = animals.reduce((sum, row) => sum + row.feed.feed_deficit_dm_kg_year, 0);
  const feedSelfSufficiency = animals.every((row) => row.feed.feed_self_sufficiency) && purchasedFeed === 0 && feedDeficit === 0;
  const reproductiveSelfSufficiency = animals.every((row) => row.reproduction?.self_replacing === true && row.reproduction?.feed_all_generations_included === true);
  const proteinCoverage = proteinTarget > 0 ? totalProtein / proteinTarget : 1;
  const nutrientCompleteness = calculateFoodNutrientAdequacy({members, plantFood, animals, energyGJ: demandGJ});
  const animalOutputByYear = Object.fromEntries(establishmentYears.map((year) => {
    const activeAnimals = animals.filter((animal) => year === 'mature' || Number(year) >= Number(animal.production_start_year ?? 1));
    return [String(year), {
      food_energy_gj_year: round(activeAnimals.reduce((sum, row) => sum + Number(row.output.food_energy_gj_year ?? 0), 0)),
      protein_kg_year: round(activeAnimals.reduce((sum, row) => sum + Number(row.output.edible_protein_kg_year ?? 0), 0)),
      active_species: activeAnimals.map((row) => row.species_id)
    }];
  }));
  // Low-level nutrient screening may be called without household members. In
  // that case there is no absolute household requirement to test; the full
  // household API always supplies members and performs the requirement check.
  const absoluteAminoAdequacy = members.length === 0 || nutrientCompleteness.amino_acid_pattern?.absolute_adequacy === true;
  return {
    contract_version: LIVESTOCK_CONTRACT_VERSION,
    mode: livestockMode,
    ration_id: rationId,
    livestock_system_count: livestockSystemCount,
    livestock_scale: round(effectiveLivestockScale),
    livestock_scaling_basis: livestockScalingBasis,
    protein_demand_kg_year: round(proteinTarget),
    plant_only: {food_energy_gj_year: round(demandGJ), protein_kg_year: round(plantOnly.macro_delivered_to_household?.protein_kg ?? 0), food_area_ha: plantOnly.required_food_area_ha},
    plant_food: plantFood,
    plant_energy_demand_gj_year: round(plantDemandGJ),
    animal_food_energy_gj_year: round(animalEnergy),
    animal_protein_kg_year: round(animalProtein),
    animal_output_by_year: animalOutputByYear,
    plant_protein_kg_year: round(plantProtein),
    total_protein_kg_year: round(totalProtein),
    protein_deficit_kg_year: round(deficit),
    protein_coverage_ratio: round(proteinCoverage),
    protein_adequacy: proteinCoverage >= 1,
    animals,
    feed: {property_supply: propertyFeed, annual_feed_required_kg: round(annualFeed), fresh_growing_season_feed_kg: round(Math.max(0, annualFeed - winterFeed)), winter_stored_feed_required_kg: round(winterFeed), winter_stored_feed_available_kg: round(animals.reduce((sum, row) => sum + row.feed.winter_stored_feed_available_kg_year, 0)), winter_feed_deficit_kg: round(animals.reduce((sum, row) => sum + row.feed.winter_feed_deficit_kg_year, 0)), storage_loss_kg: round(animals.reduce((sum, row) => sum + row.feed.storage_loss_kg_year, 0)), purchased_feed_required_kg: round(purchasedFeed), purchased_feed_dm_kg_year: round(purchasedFeed), property_grown_dedicated_feed_dm_kg_year: round(animals.reduce((sum, row) => sum + row.feed.property_grown_dedicated_feed_dm_kg_year, 0)), human_edible_feed_protein_consumed_kg: round(animals.reduce((sum, row) => sum + row.feed.human_edible_feed_protein_kg_year, 0)), human_inedible_feed_dm_kg: round(animals.reduce((sum, row) => sum + row.feed.human_inedible_feed_dm_kg_year, 0)), additional_dedicated_feed_land_ha: round(dedicatedFeedLand), feed_deficit_dm_kg_year: round(feedDeficit), feed_self_sufficiency: feedSelfSufficiency, external_feed_energy_gj_year: round(animals.reduce((sum, row) => sum + row.feed.feed_energy_import_gj_year, 0)), additional_dedicated_feed_land_if_no_purchased_substitution_ha: round(dedicatedFeedLand), double_counting_note: propertyFeed.double_counting_rule},
    labour: {recurring_hours_year: round(animals.reduce((sum, row) => sum + row.labour.recurring_hours_year, 0)), slaughter_processing_hours_year: round(animals.reduce((sum, row) => sum + row.labour.slaughter_processing_hours_year, 0)), livestock_hours_year: round(animals.reduce((sum, row) => sum + row.labour.total_hours_year, 0))},
    feed_self_sufficiency: feedSelfSufficiency,
    energy_adequacy: Number(plantFood.delivered_food_energy_gj ?? 0) + animalEnergy >= Number(demandGJ) - 1e-9,
    nutrient_completeness: nutrientCompleteness,
    reproductive_self_sufficiency: reproductiveSelfSufficiency,
    optimizer_eligible: proteinCoverage >= 1 && absoluteAminoAdequacy && Number(demandGJ) > 0 && feedSelfSufficiency && (livestockMode === 'plants_only' || reproductiveSelfSufficiency) && purchasedFeed === 0 && feedDeficit === 0,
    optimizer_note: livestockMode === 'plants_only' ? 'Plants-only is a valid baseline. Livestock is not required unless it improves a selected nutrient, land or labour objective.' : (!reproductiveSelfSufficiency ? 'This livestock option is non-canonical because the production population is not self-replacing or all generations are not fed.' : (!feedSelfSufficiency ? 'This livestock option is not ARC-feasible because the property cannot supply all dietary feed without imports.' : (deficit > 0 ? 'This on-site animal option supplies part of the remaining total-protein deficit; quality and micronutrients remain unresolved.' : 'This explicit on-site animal option meets the modeled total-protein target, but it is not automatically land-optimal.'))),
    evidence_boundary: 'Feed quantities, edible outputs and property co-product yields are bounded planning syntheses from government/extension sources, not Grey-Bruce household trials. Human-edible feed competition is tracked separately from total feed conversion.'
  };
}

export function compareNutrientFoodSystems({foodEvidence, demandGJ, proteinDemandKgYear, members = [], siteCapability} = {}) {
  const modes = ['plants_only', 'rabbit_meat', 'chicken_eggs', 'chicken_meat', 'goose_meat', 'goat_meat', 'mixed_rabbit_eggs'];
  const rationIds = ['conventional_reference', 'low_food_competition', 'arc_integrated'];
  const rows = modes.flatMap((mode) => rationIds.map((rationId) => calculateNutrientFoodSystem({foodEvidence, demandGJ, proteinDemandKgYear, members, siteCapability, livestockMode: mode, rationId}))).filter((row) => row.mode === 'plants_only' ? row.ration_id === 'arc_integrated' : true);
  const eligible = rows.filter((row) => row.protein_adequacy && row.energy_adequacy && row.optimizer_eligible && row.feed_self_sufficiency);
  const foodFeedArea = (row) => Number(row.plant_food.required_food_area_ha ?? 0) + Number(row.feed.additional_dedicated_feed_land_ha ?? 0);
  const labour = (row) => Number(row.labour?.livestock_hours_year ?? 0);
  const edibleCompetition = (row) => Number(row.feed.human_edible_feed_protein_consumed_kg ?? 0);
  const externalInputs = (row) => Number((row.nutrient_completeness?.external_inputs ?? []).length);
  const nutritionalCompleteness = (row) => Object.values(row.nutrient_completeness?.nutrients ?? {}).filter((item) => item.status === 'adequate from property-produced food').length + (row.nutrient_completeness?.amino_acid_pattern?.absolute_adequacy ? Object.keys(row.nutrient_completeness.amino_acid_pattern.rows).length : 0);
  const complexity = (row) => row.mode === 'plants_only' ? 0 : row.mode === 'mixed_rabbit_eggs' ? 2 : 1;
  const bestBy = (metric) => eligible.reduce((bestRow, row) => !bestRow || metric(row) < metric(bestRow) ? row : bestRow, null);
  const bestByDescending = (metric) => eligible.reduce((bestRow, row) => !bestRow || metric(row) > metric(bestRow) ? row : bestRow, null);
  const best = bestBy(foodFeedArea);
  const objectiveRow = (row, value, unit) => row ? {mode: row.mode, ration_id: row.ration_id, value, unit} : null;
  const metrics = (row) => ({food_feed_area_ha: foodFeedArea(row), labour_hours_year: labour(row), external_nutrient_inputs: externalInputs(row), human_edible_feed_protein_kg_year: edibleCompetition(row), nutritional_completeness_score: nutritionalCompleteness(row), complexity_units: complexity(row)});
  const pareto = eligible.filter((candidate) => {
    const a = metrics(candidate);
    return !eligible.some((other) => {
      if (other === candidate) return false;
      const b = metrics(other);
      const noWorse = b.food_feed_area_ha <= a.food_feed_area_ha && b.labour_hours_year <= a.labour_hours_year && b.external_nutrient_inputs <= a.external_nutrient_inputs && b.human_edible_feed_protein_kg_year <= a.human_edible_feed_protein_kg_year && b.complexity_units <= a.complexity_units && b.nutritional_completeness_score >= a.nutritional_completeness_score;
      const strictlyBetter = b.food_feed_area_ha < a.food_feed_area_ha || b.labour_hours_year < a.labour_hours_year || b.external_nutrient_inputs < a.external_nutrient_inputs || b.human_edible_feed_protein_kg_year < a.human_edible_feed_protein_kg_year || b.complexity_units < a.complexity_units || b.nutritional_completeness_score > a.nutritional_completeness_score;
      return noWorse && strictlyBetter;
    });
  }).map((row) => ({mode: row.mode, ration_id: row.ration_id, metrics: metrics(row)}));
  return {
    rows,
    eligible_rows: eligible.map((row) => ({mode: row.mode, ration_id: row.ration_id, metrics: metrics(row)})),
    objectives: {
      lowest_food_feed_area: objectiveRow(best, best ? foodFeedArea(best) : null, 'ha'),
      lowest_peak_productive_land: {status: 'requires full household transition context'},
      lowest_mature_productive_land: {status: 'requires full household transition context'},
      lowest_labour: objectiveRow(bestBy(labour), bestBy(labour) ? labour(bestBy(labour)) : null, 'hours/year'),
      lowest_external_nutrient_dependence: objectiveRow(bestBy(externalInputs), bestBy(externalInputs) ? externalInputs(bestBy(externalInputs)) : null, 'tracked nutrients'),
      lowest_human_edible_feed_competition: objectiveRow(bestBy(edibleCompetition), bestBy(edibleCompetition) ? edibleCompetition(bestBy(edibleCompetition)) : null, 'kg protein/year'),
      maximum_nutritional_completeness: objectiveRow(bestByDescending(nutritionalCompleteness), bestByDescending(nutritionalCompleteness) ? nutritionalCompleteness(bestByDescending(nutritionalCompleteness)) : null, 'tracked adequacy rows'),
      lowest_complexity: objectiveRow(bestBy(complexity), bestBy(complexity) ? complexity(bestBy(complexity)) : null, 'system units'),
      note: 'No single best food system is implied. Peak and mature productive-land winners require the full establishment transition; Pareto rows retain distinct land, labour, external-input, feed-competition, completeness and complexity objectives.'
    },
    pareto_efficient_options: pareto,
    best: best ? {mode: best.mode, ration_id: best.ration_id, reason: 'Lowest modeled plant-food plus on-site dedicated-feed screening area among eligible rows; not a universal optimum.', objective: 'food_feed_area_screening'} : null
  };
}
