import {calculateHouseholdProteinDemand} from './protein.mjs';

const round = (value, digits = 6) => Math.round(Number(value) * 10 ** digits) / 10 ** digits;

export const LIVESTOCK_CONTRACT_VERSION = '1.1.0';

const SOURCE = {
  rabbit: 'https://files.ontario.ca/omafra-starting-farm-in-ontario-pub-61-en-2023-04-21.pdf; https://extension.usu.edu/washington/files/Understanding_the_Basics_of_Rabbit_Care.pdf',
  poultry: 'https://www.ontario.ca/page/introduction-poultry-nutrition; https://extension.umn.edu/small-scale-poultry/raising-chickens-eggs',
  goose: 'https://extension.psu.edu/poultry-nutrition-and-feeding; https://extension.psu.edu/geese-ducks-and-swans',
  goat: 'https://files.ontario.ca/omafra-pasture-production-en-2022-12-08.pdf; https://www.gov.mb.ca/agriculture/livestock/goat/pubs/goats-and-their-nutrition.pdf',
  composition: 'https://open.canada.ca/data/en/dataset/1b6139bd-ed7e-4043-bc28-ff00e10f3109'
};

/**
 * Feed streams are deliberately separate from crop hectares. A zero land
 * requirement means the stream is a by-product, browse or overlay already
 * generated by the modeled property; it is not unlimited free feed.
 */
export const LIVESTOCK_FEED_STREAMS = {
  human_food_grade: {label: 'Human-food-grade crop', class: 'human_food_grade', dry_matter_energy_mj_kg: 15, protein_fraction: .18, human_edible_fraction: 1, winter_storage: true, storage_loss_fraction: .10, land_required: true, dedicated_feed_dm_yield_kg_ha: 2500, evidence_status: 'derived_food_system_input; local feed-crop planning synthesis', source: SOURCE.composition},
  human_edible_surplus: {label: 'Human-edible surplus', class: 'human_edible_surplus', dry_matter_energy_mj_kg: 14, protein_fraction: .16, human_edible_fraction: 1, winter_storage: true, storage_loss_fraction: .10, land_required: false, local_replacement_stream: 'human_food_grade', evidence_status: 'derived_after_human_food_priority', source: SOURCE.composition},
  crop_byproduct: {label: 'Crop by-product', class: 'crop_byproduct', dry_matter_energy_mj_kg: 10, protein_fraction: .10, human_edible_fraction: .15, winter_storage: true, storage_loss_fraction: .12, land_required: false, local_replacement_stream: 'human_food_grade', evidence_status: 'planning_synthesis', source: SOURCE.composition},
  garden_cull: {label: 'Garden cull', class: 'garden_cull', dry_matter_energy_mj_kg: 11, protein_fraction: .12, human_edible_fraction: .30, winter_storage: false, storage_loss_fraction: .20, land_required: false, local_replacement_stream: 'human_food_grade', evidence_status: 'planning_synthesis', source: SOURCE.composition},
  herbaceous_forage: {label: 'Herbaceous forage', class: 'herbaceous_forage', dry_matter_energy_mj_kg: 9, protein_fraction: .12, human_edible_fraction: 0, winter_storage: true, storage_loss_fraction: .15, land_required: true, dedicated_feed_dm_yield_kg_ha: 4000, evidence_status: 'extension_bounded_planning_synthesis', source: 'https://extension.psu.edu/average-nutrient-composition-of-typical-high-quality-pastures-dry-matter-basis'},
  pasture: {label: 'Pasture', class: 'pasture', dry_matter_energy_mj_kg: 9.5, protein_fraction: .15, human_edible_fraction: 0, winter_storage: false, storage_loss_fraction: .20, land_required: true, dedicated_feed_dm_yield_kg_ha: 2500, evidence_status: 'extension_bounded_planning_synthesis', source: 'https://extension.psu.edu/average-nutrient-composition-of-typical-high-quality-pastures-dry-matter-basis'},
  hay: {label: 'Stored hay', class: 'hay', dry_matter_energy_mj_kg: 8.5, protein_fraction: .10, human_edible_fraction: 0, winter_storage: true, storage_loss_fraction: .15, land_required: true, dedicated_feed_dm_yield_kg_ha: 3500, evidence_status: 'extension_bounded_planning_synthesis', source: 'https://www.ontario.ca/page/pasture-production'},
  leaf_fodder: {label: 'Food-forest leaf fodder', class: 'leaf_fodder', dry_matter_energy_mj_kg: 8, protein_fraction: .12, human_edible_fraction: 0, winter_storage: true, storage_loss_fraction: .20, land_required: true, dedicated_feed_dm_yield_kg_ha: 1000, evidence_status: 'planning_synthesis_requires_site_inventory', source: SOURCE.goat},
  woody_browse: {label: 'Woody browse', class: 'woody_browse', dry_matter_energy_mj_kg: 7.5, protein_fraction: .10, human_edible_fraction: 0, winter_storage: true, storage_loss_fraction: .25, land_required: true, dedicated_feed_dm_yield_kg_ha: 1500, evidence_status: 'extension_bounded_planning_synthesis_requires_browse_inventory', source: SOURCE.goat},
  food_forest_understorey: {label: 'Food-forest understorey', class: 'food_forest_understorey', dry_matter_energy_mj_kg: 8.5, protein_fraction: .12, human_edible_fraction: 0, winter_storage: true, storage_loss_fraction: .18, land_required: true, dedicated_feed_dm_yield_kg_ha: 1500, evidence_status: 'planning_synthesis_requires_site_inventory', source: SOURCE.goat},
  invertebrate: {label: 'Invertebrates', class: 'invertebrate', dry_matter_energy_mj_kg: 12, protein_fraction: .45, human_edible_fraction: .05, winter_storage: false, storage_loss_fraction: .25, land_required: false, local_replacement_stream: 'human_food_grade', evidence_status: 'planning_synthesis', source: SOURCE.poultry},
  purchased_concentrate: {label: 'Purchased concentrate', class: 'purchased_concentrate', dry_matter_energy_mj_kg: 12, protein_fraction: .18, human_edible_fraction: .90, winter_storage: true, storage_loss_fraction: .05, land_required: false, evidence_status: 'external_input_reference', source: SOURCE.poultry},
  mineral_supplement: {label: 'Mineral supplement', class: 'mineral_supplement', dry_matter_energy_mj_kg: 0, protein_fraction: 0, human_edible_fraction: 1, winter_storage: true, storage_loss_fraction: 0, land_required: false, evidence_status: 'health_requirement_not_food_energy', source: SOURCE.poultry}
};

const species = {
  rabbit_meat: {
    id: 'rabbit_meat', label: 'Rabbit meat', animal: 'Rabbit', unit_label: '48-fryer household rabbitry plus breeding stock', output: {edible_meat_kg_year: 40.8, food_energy_gj_year: .232, edible_protein_kg_year: 8.89, edible_fat_kg_year: 1.43}, feed_dm_kg_year: 350, winter_fraction: .60, housing_area_m2: 12, fencing_m: 25, water_l_day: 35, labour_hours_year: 180, physical_labour: 'moderate-high', slaughter_processing_hours_year: 45, manure_kg_year: 300, production_start_year: 1, sources: [SOURCE.rabbit], notes: 'Balanced rabbit feed remains required; forage and leaves are bounded supplements rather than an assumption of grass-only production.'
  },
  chicken_eggs: {
    id: 'chicken_eggs', label: 'Laying hens / eggs', animal: 'Chicken', unit_label: '6 laying hens', output: {eggs_kg_year: 72.6, eggs_year: 1320, food_energy_gj_year: .448, edible_protein_kg_year: 9.15, edible_fat_kg_year: 7.70}, feed_dm_kg_year: 425.2, winter_fraction: .45, housing_area_m2: 6, fencing_m: 20, water_l_day: 3, labour_hours_year: 120, physical_labour: 'moderate', slaughter_processing_hours_year: 0, manure_kg_year: 300, production_start_year: 1, sources: [SOURCE.poultry], notes: 'A complete ration, calcium, grit and clean water remain required; scraps and pasture cannot replace balanced layer nutrition.'
  },
  chicken_meat: {
    id: 'chicken_meat', label: 'Meat chickens', animal: 'Chicken', unit_label: '25 meat birds per year', output: {edible_meat_kg_year: 35, food_energy_gj_year: .42, edible_protein_kg_year: 7.0, edible_fat_kg_year: 5.6}, feed_dm_kg_year: 125, winter_fraction: .25, housing_area_m2: 8, fencing_m: 25, water_l_day: 12, labour_hours_year: 150, physical_labour: 'moderate', slaughter_processing_hours_year: 60, manure_kg_year: 180, production_start_year: 1, sources: [SOURCE.poultry], notes: 'Reference smallholder output; feed and processing are planning assumptions and not a claim of pasture-only growth.'
  },
  goose_meat: {
    id: 'goose_meat', label: 'Grazing-biased geese', animal: 'Goose', unit_label: '8 geese annual meat flock', output: {edible_meat_kg_year: 24, food_energy_gj_year: .34, edible_protein_kg_year: 5.0, edible_fat_kg_year: 3.8}, feed_dm_kg_year: 1050, winter_fraction: .35, housing_area_m2: 10, fencing_m: 45, water_l_day: 16, labour_hours_year: 160, physical_labour: 'moderate', slaughter_processing_hours_year: 36, manure_kg_year: 850, production_start_year: 1, sources: [SOURCE.goose], notes: 'Pasture contribution is substantial but seasonal; winter feed, shelter, water and supplemental ration remain necessary.'
  },
  goat_meat: {
    id: 'goat_meat', label: 'Browse-biased goats', animal: 'Goat', unit_label: '2 mature does plus annual meat-kid output', output: {edible_meat_kg_year: 30, food_energy_gj_year: .43, edible_protein_kg_year: 6.0, edible_fat_kg_year: 4.5}, feed_dm_kg_year: 1200, winter_fraction: .55, housing_area_m2: 14, fencing_m: 120, water_l_day: 12, labour_hours_year: 260, physical_labour: 'high', slaughter_processing_hours_year: 50, manure_kg_year: 950, production_start_year: 2, sources: [SOURCE.goat], notes: 'Goats can browse a large share of their diet, but browse inventory, fencing, hay and winter supplementation are site-specific.'
  }
};

export const LIVESTOCK_SPECIES = species;

export const LIVESTOCK_RATION_SCENARIOS = {
  conventional_reference: {
    id: 'conventional_reference', label: 'External-feed sensitivity (non-ARC)', description: 'Normal smallholder reference ration with external feed; shown only as a sensitivity and excluded from canonical ARC optimization.', allow_purchased_feed: true, canonical_arc: false,
    shares: {rabbit_meat: {purchased_concentrate: .60, hay: .25, crop_byproduct: .10, herbaceous_forage: .05}, chicken_eggs: {purchased_concentrate: .80, human_food_grade: .10, garden_cull: .10}, chicken_meat: {purchased_concentrate: .80, crop_byproduct: .10, garden_cull: .10}, goose_meat: {pasture: .35, herbaceous_forage: .25, hay: .15, purchased_concentrate: .25}, goat_meat: {hay: .45, woody_browse: .30, purchased_concentrate: .25}}
  },
  low_food_competition: {
    id: 'low_food_competition', label: 'Low-food-competition sensitivity (non-ARC)', description: 'Maximizes forage, browse, culls and residues while retaining external supplements; not ARC feed self-sufficiency compliant.', allow_purchased_feed: true, canonical_arc: false,
    shares: {rabbit_meat: {herbaceous_forage: .35, leaf_fodder: .20, hay: .20, crop_byproduct: .15, purchased_concentrate: .10}, chicken_eggs: {garden_cull: .25, invertebrate: .10, crop_byproduct: .15, human_edible_surplus: .10, purchased_concentrate: .40}, chicken_meat: {garden_cull: .20, invertebrate: .10, crop_byproduct: .20, human_edible_surplus: .10, purchased_concentrate: .40}, goose_meat: {pasture: .45, herbaceous_forage: .20, hay: .15, crop_byproduct: .10, purchased_concentrate: .10}, goat_meat: {woody_browse: .55, leaf_fodder: .20, hay: .15, purchased_concentrate: .10}}
  },
  arc_integrated: {
    id: 'arc_integrated', label: 'ARC on-site feed', description: 'All dietary feed energy and protein is produced on the ARC property through finite co-products and dedicated feed hectares. Purchased feed is prohibited.', allow_purchased_feed: false, canonical_arc: true,
    shares: {rabbit_meat: {herbaceous_forage: .25, leaf_fodder: .20, crop_byproduct: .15, food_forest_understorey: .15, hay: .25}, chicken_eggs: {garden_cull: .25, invertebrate: .15, crop_byproduct: .15, human_edible_surplus: .10, human_food_grade: .35}, chicken_meat: {garden_cull: .20, invertebrate: .15, crop_byproduct: .20, human_edible_surplus: .10, human_food_grade: .35}, goose_meat: {pasture: .45, herbaceous_forage: .25, crop_byproduct: .10, hay: .20}, goat_meat: {woody_browse: .55, leaf_fodder: .20, hay: .25}}
  }
};

export const PROPERTY_FEED_SUPPLY_RULES = {
  crop_byproduct_kg_dm_per_ha_annual_food: 250,
  garden_cull_kg_dm_per_ha_annual_food: 80,
  food_forest_understorey_kg_dm_per_ha_perennial_food: 180,
  leaf_fodder_kg_dm_per_ha_perennial_food: 80,
  woody_browse_kg_dm_per_ha_perennial_food: 120,
  herbaceous_forage_kg_dm_per_ha_perennial_food: 160,
  pasture_kg_dm_per_ha: 0,
  invertebrate_kg_dm_per_ha_food_area: 30,
  status: 'explicit planning synthesis; requires a property biomass inventory before operational use',
  double_counting_rule: 'These are finite co-products/overlays within the modeled food areas. Dedicated feed hectares are added for any shortfall; the same stream is not assigned twice.'
};

function normalizedShares(shares = {}) {
  const total = Object.values(shares).reduce((sum, value) => sum + Number(value), 0);
  if (!(total > 0)) throw new Error('livestock ration must contain a positive feed share');
  return Object.fromEntries(Object.entries(shares).map(([id, value]) => [id, Number(value) / total]));
}

export function derivePropertyFeedSupply({foodSystem = {}} = {}) {
  const foodArea = Number(foodSystem.required_food_area_ha ?? 0);
  const annualArea = foodArea * .25;
  const perennialArea = foodArea * .75;
  const rules = PROPERTY_FEED_SUPPLY_RULES;
  return {
    crop_byproduct: annualArea * rules.crop_byproduct_kg_dm_per_ha_annual_food,
    garden_cull: foodArea * rules.garden_cull_kg_dm_per_ha_annual_food,
    food_forest_understorey: perennialArea * rules.food_forest_understorey_kg_dm_per_ha_perennial_food,
    leaf_fodder: perennialArea * rules.leaf_fodder_kg_dm_per_ha_perennial_food,
    woody_browse: perennialArea * rules.woody_browse_kg_dm_per_ha_perennial_food,
    herbaceous_forage: perennialArea * rules.herbaceous_forage_kg_dm_per_ha_perennial_food,
    pasture: 0,
    invertebrate: foodArea * rules.invertebrate_kg_dm_per_ha_food_area,
    human_edible_surplus: 0,
    source: rules.status,
    food_area_basis_ha: foodArea,
    double_counting_rule: rules.double_counting_rule
  };
}

export function calculateFeedLedger({speciesId, rationId = 'arc_integrated', scale = 1, propertyFeedSupply = {}, siteCapability = {}, requireSelfSufficient = null} = {}) {
  const animal = LIVESTOCK_SPECIES[speciesId];
  const ration = LIVESTOCK_RATION_SCENARIOS[rationId] ?? LIVESTOCK_RATION_SCENARIOS.arc_integrated;
  if (!animal) throw new Error(`Unknown livestock species: ${speciesId}`);
  const shares = normalizedShares(ration.shares[speciesId]);
  const totalDm = Number(animal.feed_dm_kg_year) * Number(scale);
  const selfSufficient = requireSelfSufficient ?? !ration.allow_purchased_feed;
  const feedYieldMultiplier = Math.max(0, Number(siteCapability.feed_yield_multiplier ?? siteCapability.food_yield_multiplier ?? 1));
  const rows = Object.entries(shares).map(([streamId, share]) => {
    const stream = LIVESTOCK_FEED_STREAMS[streamId];
    if (!stream) throw new Error(`Unknown feed stream: ${streamId}`);
    const required = totalDm * share;
    const available = Math.max(0, Number(propertyFeedSupply[streamId] ?? 0));
    const onProperty = Math.min(required, available);
    const unmet = Math.max(0, required - onProperty);
    const producerId = stream.dedicated_feed_dm_yield_kg_ha > 0 ? streamId : stream.local_replacement_stream;
    const producer = producerId ? LIVESTOCK_FEED_STREAMS[producerId] : null;
    const producerYield = Number(producer?.dedicated_feed_dm_yield_kg_ha ?? 0) * feedYieldMultiplier;
    const localProductionPossible = selfSufficient && unmet > 0 && producer && producerYield > 0;
    const dedicatedConsumed = localProductionPossible ? unmet : 0;
    const storageFactor = stream.winter_storage ? Math.max(.01, 1 - Number(producer?.storage_loss_fraction ?? stream.storage_loss_fraction ?? 0)) : 1;
    const dedicatedProduction = localProductionPossible ? dedicatedConsumed / storageFactor : 0;
    const dedicatedLand = localProductionPossible ? dedicatedProduction / producerYield : 0;
    const purchased = !selfSufficient ? unmet : 0;
    const unresolved = selfSufficient ? (localProductionPossible ? 0 : unmet) : 0;
    const components = [{dm: onProperty, source: stream}, {dm: dedicatedConsumed, source: producer}, {dm: purchased, source: stream}].filter((component) => component.source && component.dm > 0);
    const actual = (field, fallback = 0) => components.reduce((sum, component) => sum + component.dm * Number(component.source?.[field] ?? fallback), 0);
    return {stream_id: streamId, stream_label: stream.label, class: stream.class, required_dm_kg: round(required), on_property_dm_kg: round(onProperty), dedicated_feed_dm_kg: round(dedicatedProduction), dedicated_feed_land_ha: round(dedicatedLand), dedicated_consumed_dm_kg: round(dedicatedConsumed), local_production_stream_id: localProductionPossible ? producerId : null, purchased_dm_kg: round(purchased), unresolved_feed_deficit_dm_kg: round(unresolved), total_feed_energy_gj: round(actual('dry_matter_energy_mj_kg') / 1000), total_feed_protein_kg: round(actual('protein_fraction')), human_edible_feed_dm_kg: round(actual('human_edible_fraction')), human_edible_feed_protein_kg: round(components.reduce((sum, component) => sum + component.dm * Number(component.source?.protein_fraction ?? 0) * Number(component.source?.human_edible_fraction ?? 0), 0)), on_property_human_edible_feed_protein_kg: round(onProperty * stream.protein_fraction * stream.human_edible_fraction), property_grown_dedicated_human_edible_feed_protein_kg: round(dedicatedConsumed * Number(producer?.protein_fraction ?? 0) * Number(producer?.human_edible_fraction ?? 0)), winter_stored_dm_kg: stream.winter_storage ? round(required) : 0, winter_stored_dm_available_kg: stream.winter_storage ? round(onProperty + dedicatedConsumed + purchased) : 0, storage_loss_dm_kg: round(Math.max(0, dedicatedProduction - dedicatedConsumed)), human_edible_fraction: stream.human_edible_fraction, evidence_status: stream.evidence_status, source: stream.source};
  });
  const required = rows.reduce((sum, row) => sum + row.required_dm_kg, 0);
  const property = rows.reduce((sum, row) => sum + row.on_property_dm_kg, 0);
  const dedicatedProduction = rows.reduce((sum, row) => sum + row.dedicated_feed_dm_kg, 0);
  const dedicatedLand = rows.reduce((sum, row) => sum + row.dedicated_feed_land_ha, 0);
  const purchased = rows.reduce((sum, row) => sum + row.purchased_dm_kg, 0);
  const winter = rows.reduce((sum, row) => sum + row.winter_stored_dm_kg, 0);
  const winterAvailable = rows.reduce((sum, row) => sum + row.winter_stored_dm_available_kg, 0);
  const unresolved = rows.reduce((sum, row) => sum + row.unresolved_feed_deficit_dm_kg, 0);
  return {
    species_id: speciesId,
    ration_id: ration.id,
    rows,
    dry_matter_requirement_kg_year: round(required),
    on_property_dry_matter_kg_year: round(property),
    purchased_dry_matter_kg_year: round(purchased),
    property_grown_dedicated_feed_dm_kg_year: round(dedicatedProduction),
    additional_dedicated_feed_land_ha: round(dedicatedLand),
    feed_deficit_dm_kg_year: round(unresolved),
    human_edible_feed_dm_kg_year: round(rows.reduce((sum, row) => sum + row.human_edible_feed_dm_kg, 0)),
    human_inedible_feed_dm_kg_year: round(rows.reduce((sum, row) => sum + row.required_dm_kg - row.human_edible_feed_dm_kg, 0)),
    feed_protein_kg_year: round(rows.reduce((sum, row) => sum + row.total_feed_protein_kg, 0)),
    human_edible_feed_protein_kg_year: round(rows.reduce((sum, row) => sum + row.human_edible_feed_protein_kg, 0)),
    on_property_human_edible_feed_protein_kg_year: round(rows.reduce((sum, row) => sum + row.on_property_human_edible_feed_protein_kg, 0)),
    winter_stored_feed_required_kg_year: round(winter),
    winter_stored_feed_available_kg_year: round(winterAvailable),
    winter_feed_deficit_kg_year: round(Math.max(0, winter - winterAvailable)),
    storage_loss_kg_year: round(rows.reduce((sum, row) => sum + row.storage_loss_dm_kg, 0)),
    purchased_feed_required: purchased > 0,
    feed_self_sufficiency: unresolved === 0 && purchased === 0 && winterAvailable >= winter,
    feed_energy_import_gj_year: round(rows.reduce((sum, row) => sum + row.purchased_dm_kg * (LIVESTOCK_FEED_STREAMS[row.stream_id]?.dry_matter_energy_mj_kg ?? 0) / 1000, 0)),
    source: animal.sources,
    ration_description: ration.description
  };
}

export function calculateLivestockScenario({speciesId, rationId = 'arc_integrated', scale = 1, propertyFeedSupply = {}, siteCapability = {}, requireSelfSufficient = null} = {}) {
  const animal = LIVESTOCK_SPECIES[speciesId];
  const feed = calculateFeedLedger({speciesId, rationId, scale, propertyFeedSupply, siteCapability, requireSelfSufficient});
  const outputScale = Number(scale);
  const edibleProtein = Number(animal.output.edible_protein_kg_year) * outputScale;
  return {
    species_id: speciesId,
    label: animal.label,
    animal: animal.animal,
    unit_label: animal.unit_label,
    scale: outputScale,
    output: Object.fromEntries(Object.entries(animal.output).map(([key, value]) => [key, round(Number(value) * outputScale)])),
    feed,
    net_human_edible_protein_kg_year: round(edibleProtein - feed.human_edible_feed_protein_kg_year),
    human_edible_protein_conversion_efficiency: feed.human_edible_feed_protein_kg_year > 0 ? round(edibleProtein / feed.human_edible_feed_protein_kg_year, 4) : null,
    human_inedible_feed_fraction: feed.dry_matter_requirement_kg_year > 0 ? round(feed.human_inedible_feed_dm_kg_year / feed.dry_matter_requirement_kg_year) : 0,
    housing: {area_m2: round(animal.housing_area_m2 * outputScale), fencing_m: round(animal.fencing_m * outputScale), water_l_day: round(animal.water_l_day * outputScale)},
    labour: {recurring_hours_year: round(animal.labour_hours_year * outputScale), slaughter_processing_hours_year: round(animal.slaughter_processing_hours_year * outputScale), total_hours_year: round((animal.labour_hours_year + animal.slaughter_processing_hours_year) * outputScale), physical_intensity: animal.physical_labour},
    manure_kg_year: round(animal.manure_kg_year * outputScale),
    production_start_year: animal.production_start_year,
    source: animal.sources,
    evidence_status: 'planning_synthesis_bounded_by_extension_and_government_guidance',
    notes: animal.notes
  };
}

export function calculateNutrientFoodSystem({foodEvidence, demandGJ, proteinDemandKgYear, siteCapability, livestockMode = 'plants_only', rationId = 'arc_integrated', livestockScale = 1, establishmentYears = [1, 2, 3, 5, 8, 10, 15, 'mature']} = {}) {
  if (!foodEvidence) throw new Error('nutrient food system requires canonical food evidence');
  const {calculateFoodSystem} = siteCapability?.calculateFoodSystem ? siteCapability : {};
  if (typeof calculateFoodSystem !== 'function') throw new Error('nutrient food system requires calculateFoodSystem in siteCapability');
  const plantOnly = calculateFoodSystem(foodEvidence, demandGJ, siteCapability);
  const proteinTarget = Number(proteinDemandKgYear ?? 0);
  const modes = livestockMode === 'plants_only' ? [] : livestockMode === 'mixed_rabbit_eggs' ? ['rabbit_meat', 'chicken_eggs'] : [livestockMode];
  const animalOutputs = modes.map((speciesId) => calculateLivestockScenario({speciesId, rationId, scale: livestockScale, propertyFeedSupply: {}, siteCapability}));
  const animalEnergy = animalOutputs.reduce((sum, row) => sum + Number(row.output.food_energy_gj_year ?? 0), 0);
  const animalProtein = animalOutputs.reduce((sum, row) => sum + Number(row.output.edible_protein_kg_year ?? 0), 0);
  const plantDemandGJ = Math.max(0, Number(demandGJ) - animalEnergy);
  const plantFood = plantDemandGJ === Number(demandGJ) ? plantOnly : calculateFoodSystem(foodEvidence, plantDemandGJ, siteCapability);
  const plantProtein = Number(plantFood.macro_delivered_to_household?.protein_kg ?? 0);
  const totalProtein = plantProtein + animalProtein;
  const deficit = Math.max(0, proteinTarget - totalProtein);
  const propertyFeed = derivePropertyFeedSupply({foodSystem: plantFood});
  const remainingPropertyFeed = {...propertyFeed};
  const animals = animalOutputs.map((row) => {
    const result = calculateLivestockScenario({speciesId: row.species_id, rationId, scale: row.scale, propertyFeedSupply: remainingPropertyFeed, siteCapability});
    for (const feedRow of result.feed.rows) remainingPropertyFeed[feedRow.stream_id] = Math.max(0, Number(remainingPropertyFeed[feedRow.stream_id] ?? 0) - Number(feedRow.on_property_dm_kg ?? 0));
    return result;
  });
  const annualFeed = animals.reduce((sum, row) => sum + row.feed.dry_matter_requirement_kg_year, 0);
  const winterFeed = animals.reduce((sum, row) => sum + row.feed.winter_stored_feed_required_kg_year, 0);
  const purchasedFeed = animals.reduce((sum, row) => sum + row.feed.purchased_dry_matter_kg_year, 0);
  const dedicatedFeedLand = animals.reduce((sum, row) => sum + row.feed.additional_dedicated_feed_land_ha, 0);
  const feedDeficit = animals.reduce((sum, row) => sum + row.feed.feed_deficit_dm_kg_year, 0);
  const feedSelfSufficiency = animals.every((row) => row.feed.feed_self_sufficiency) && purchasedFeed === 0 && feedDeficit === 0;
  const proteinCoverage = proteinTarget > 0 ? totalProtein / proteinTarget : 1;
  const animalOutputByYear = Object.fromEntries(establishmentYears.map((year) => {
    const activeAnimals = animals.filter((animal) => year === 'mature' || Number(year) >= Number(animal.production_start_year ?? 1));
    return [String(year), {
      food_energy_gj_year: round(activeAnimals.reduce((sum, row) => sum + Number(row.output.food_energy_gj_year ?? 0), 0)),
      protein_kg_year: round(activeAnimals.reduce((sum, row) => sum + Number(row.output.edible_protein_kg_year ?? 0), 0)),
      active_species: activeAnimals.map((row) => row.species_id)
    }];
  }));
  return {
    contract_version: LIVESTOCK_CONTRACT_VERSION,
    mode: livestockMode,
    ration_id: rationId,
    protein_demand_kg_year: round(proteinTarget),
    plant_only: {food_energy_gj_year: round(demandGJ), protein_kg_year: round(plantOnly.macro_delivered_to_household?.protein_kg ?? 0), food_area_ha: plantOnly.required_food_area_ha},
    plant_food: plantFood,
    plant_energy_demand_gj_year: round(plantDemandGJ),
    animal_food_energy_gj_year: round(animalEnergy),
    animal_protein_kg_year: round(animalProtein),
    animal_output_by_year: animalOutputByYear,
    plant_protein_kg_year: round(plantProtein),
    total_protein_kg_year: round(totalProtein),
    protein_deficit_kg_year: round(deficit),
    protein_coverage_ratio: round(proteinCoverage),
    protein_adequacy: proteinCoverage >= 1,
    animals,
    feed: {property_supply: propertyFeed, annual_feed_required_kg: round(annualFeed), fresh_growing_season_feed_kg: round(Math.max(0, annualFeed - winterFeed)), winter_stored_feed_required_kg: round(winterFeed), winter_stored_feed_available_kg: round(animals.reduce((sum, row) => sum + row.feed.winter_stored_feed_available_kg_year, 0)), winter_feed_deficit_kg: round(animals.reduce((sum, row) => sum + row.feed.winter_feed_deficit_kg_year, 0)), storage_loss_kg: round(animals.reduce((sum, row) => sum + row.feed.storage_loss_kg_year, 0)), purchased_feed_required_kg: round(purchasedFeed), purchased_feed_dm_kg_year: round(purchasedFeed), property_grown_dedicated_feed_dm_kg_year: round(animals.reduce((sum, row) => sum + row.feed.property_grown_dedicated_feed_dm_kg_year, 0)), human_edible_feed_protein_consumed_kg: round(animals.reduce((sum, row) => sum + row.feed.human_edible_feed_protein_kg_year, 0)), human_inedible_feed_dm_kg: round(animals.reduce((sum, row) => sum + row.feed.human_inedible_feed_dm_kg_year, 0)), additional_dedicated_feed_land_ha: round(dedicatedFeedLand), feed_deficit_dm_kg_year: round(feedDeficit), feed_self_sufficiency: feedSelfSufficiency, external_feed_energy_gj_year: round(animals.reduce((sum, row) => sum + row.feed.feed_energy_import_gj_year, 0)), additional_dedicated_feed_land_if_no_purchased_substitution_ha: round(dedicatedFeedLand), double_counting_note: propertyFeed.double_counting_rule},
    labour: {livestock_hours_year: round(animals.reduce((sum, row) => sum + row.labour.total_hours_year, 0))},
    feed_self_sufficiency: feedSelfSufficiency,
    energy_adequacy: Number(plantFood.delivered_food_energy_gj ?? 0) + animalEnergy >= Number(demandGJ) - 1e-9,
    optimizer_eligible: livestockMode === 'plants_only' || (proteinCoverage >= 1 && feedSelfSufficiency && purchasedFeed === 0 && feedDeficit === 0),
    optimizer_note: livestockMode === 'plants_only' ? 'Plants-only is a valid baseline. Livestock is not required unless it improves the selected nutrient/land objective.' : (!feedSelfSufficiency ? 'This livestock option is not ARC-feasible because the property cannot supply all dietary feed without imports.' : (deficit > 0 ? 'This on-site animal option supplies part of the remaining total-protein deficit; quality and micronutrients remain unresolved.' : 'This explicit on-site animal option meets the modeled total-protein target, but it is not automatically land-optimal.')),
    evidence_boundary: 'Feed quantities, edible outputs and property co-product yields are bounded planning syntheses from government/extension sources, not Grey-Bruce household trials. Human-edible feed competition is tracked separately from total feed conversion.'
  };
}

export function compareNutrientFoodSystems({foodEvidence, demandGJ, proteinDemandKgYear, siteCapability} = {}) {
  const modes = ['plants_only', 'rabbit_meat', 'chicken_eggs', 'chicken_meat', 'goose_meat', 'goat_meat', 'mixed_rabbit_eggs'];
  const rationIds = ['conventional_reference', 'low_food_competition', 'arc_integrated'];
  const rows = modes.flatMap((mode) => rationIds.map((rationId) => calculateNutrientFoodSystem({foodEvidence, demandGJ, proteinDemandKgYear, siteCapability, livestockMode: mode, rationId}))).filter((row) => row.mode === 'plants_only' ? row.ration_id === 'arc_integrated' : true);
  const eligible = rows.filter((row) => row.protein_adequacy && row.energy_adequacy && row.optimizer_eligible && row.feed_self_sufficiency);
  const best = eligible.reduce((bestRow, row) => !bestRow || (row.plant_food.required_food_area_ha + row.feed.additional_dedicated_feed_land_ha) < (bestRow.plant_food.required_food_area_ha + bestRow.feed.additional_dedicated_feed_land_ha) ? row : bestRow, null);
  return {rows, best: best ? {mode: best.mode, ration_id: best.ration_id, reason: best.mode === 'plants_only' ? 'Plants-only meets the modeled total-protein target without imported feed or dedicated animal-feed land.' : 'Lowest modeled total food plus on-site feed land among protein-adequate, feed-self-sufficient options.'} : null};
}
