import fs from 'node:fs';
import path from 'node:path';
import {PACKAGE_ROOT, CARRYING_CAPACITY_CONTRACT_VERSION, loadCanonicalCarryingCapacity} from './index.mjs';
import {calculateGreyCarryingCapacityAdoption} from './regional.mjs';
import {calculateHealthCanadaEER, representativeProfiles} from './health-canada.mjs';
import {householdProfiles, siteClasses, FOOD_ADULT_EQUIVALENT_GJ_YEAR, buildingArchetypes, insulationPresets, defaultBuilding, labourCapacityLevels} from './core.mjs';
import {calculatePerennialMixTimeline} from './perennial.mjs';

export const PRESENTATION_CONTRACT_VERSION = '1.1.0';

function readJson(filePath, fallback = {}) { return fs.existsSync(filePath) ? JSON.parse(fs.readFileSync(filePath, 'utf8')) : fallback; }
function finite(value, fallback = 0) { return Number.isFinite(Number(value)) ? Number(value) : fallback; }
function metricEnergy(row) { return {mj_day: row.mj_day, gj_year: row.gj_year}; }
function publicEer(row) { return {id: row.id, label: row.label, age_y: row.age_y, sex: row.sex, weight_kg: row.weight_kg, height_cm: row.height_cm, activity: row.activity, ...metricEnergy(row), source: row.source, status: row.status}; }
function publicText(value) { return String(value ?? '').replace(/\b[\d,.]+\s*lb\/acre\b/gi, 'an imperial full-production reference').replace(/\bkcal\b/gi, 'source energy unit').replace(/\bcalories?\b/gi, 'food energy'); }
function publicize(value) { if (Array.isArray(value)) return value.map(publicize); if (value && typeof value === 'object') return Object.fromEntries(Object.entries(value).map(([key, child]) => [key, publicize(child)])); return typeof value === 'string' ? publicText(value) : value; }
function publicPerennialRow(row) { return {id: row.id, species: row.species, functional_class: row.functional_class, role: row.role, first_meaningful_crop_year: row.first_meaningful_crop_year || null, substantial_crop_year: row.substantial_crop_year || null, mature_year: row.mature_year || null, mature_yield_t_ha_year: row.mature_yield_t_ha_year === '' ? null : row.mature_yield_t_ha_year, mature_food_gj_ha_year: row.mature_food_gj_ha_year, protein_kg_ha: row.protein_kg_ha, fat_kg_ha: row.fat_kg_ha, carbohydrate_kg_ha: row.carbohydrate_kg_ha, evidence_status: row.canonical_status, evidence_type: row.evidence_type, source: row.source, geography: row.geography, climate_or_site: row.climate_or_site, model_role: row.role, notes: publicText(row.notes)}; }
function pickTransition(row) { return {year: row.year, annual_food_area_ha: row.annual_area_ha, perennial_food_area_ha: row.perennial_area_ha, occupied_food_production_area_ha: row.occupied_food_production_area_ha, annual_food_supplied_gj_year: row.annual_usable_food_gj, perennial_food_supplied_gj_year: row.perennial_usable_food_gj, food_coverage_ratio: row.household_food_coverage_ratio, exportable_food_energy_surplus_gj_year: row.exportable_food_energy_surplus_gj, labour: publicize(row.labour)}; }
function publicRegional(regional) { return {...regional, scenarios: regional.scenarios.map((scenario) => ({...scenario, transition_years: scenario.transition_years.map(({profile_rows, ...year}) => year)}))}; }

export function buildCarryingCapacityPresentationContract({produceDir = 'know/produce', generatedAt = new Date().toISOString()} = {}) {
  const canonical = loadCanonicalCarryingCapacity();
  const foodEvidence = readJson(path.join(PACKAGE_ROOT, 'data/derived/evidence-food-yields.json'));
  const perennialEvidence = readJson(path.join(PACKAGE_ROOT, 'data/derived/perennial-yield-evidence.json'));
  const heatingEvidence = readJson(path.join(PACKAGE_ROOT, 'data/derived/evidence-heating.json'));
  const woodyEvidence = readJson(path.join(PACKAGE_ROOT, 'data/derived/evidence-woody-yields.json'));
  const systemicEnergy = readJson(path.resolve(PACKAGE_ROOT, '../../data/systemic-energy/systemic-energy-v1.json'));
  const dwelling = readJson(path.resolve(produceDir, 'grey-dwelling-land-access.json'));
  const foodCalibration = readJson(path.resolve(produceDir, 'grey-food-calibration.json'));
  const landAccessProxyAvailable = dwelling.dwellingLandAccessValid !== false
    && Number.isFinite(Number(dwelling.estimatedDwellingsWithGardenScaleAccess))
    && Number.isFinite(Number(dwelling.estimatedPopulationWithGardenScaleAccess));
  const eligibleHouseholds = landAccessProxyAvailable ? finite(dwelling.estimatedDwellingsWithGardenScaleAccess) : 0;
  const eligiblePopulation = landAccessProxyAvailable ? finite(dwelling.estimatedPopulationWithGardenScaleAccess) : 0;
  const landAccessStatus = landAccessProxyAvailable ? 'available' : 'unavailable_missing_validated_proxy';
  const energyScenarios = Object.fromEntries(Object.entries(canonical.canonical.human_energy.scenarios ?? {}).map(([id, row]) => [id, publicEer(row)]));
  const publicSiteLabels = {wetter_productive: 'Favourable / productive', ordinary_mesic: 'Ordinary / mesic', shallow_rocky_marginal: 'Marginal / shallow / rocky'};
  const publicSites = Object.fromEntries(Object.keys(publicSiteLabels).map((id) => [id, {id, ...siteClasses[id], label: publicSiteLabels[id]}]));
  const referenceProfile = {id: 'reference_adult_man', label: 'Reference adult man', age_y: 35, sex: 'male', weight_kg: 75, height_cm: 178, activity: 'low'};
  const matureRows = (canonical.canonical.mature_food_system.canonical_rows ?? []).filter((row) => row.module === 'plants_only').map((row) => ({site: row.site, site_label: row.site_label, household: row.household, household_label: row.household_label, household_food_gj_year: row.household_food_gj_year, year1_annual_bridge_area_ha: row.year1_annual_bridge_area_ha, mature_annual_area_ha: row.mature_annual_area_ha, mature_perennial_area_ha: row.mature_perennial_area_ha, heating_area_ha: row.heating_area_ha, robust_household_minimum_area_ha: row.robust_household_minimum_area_ha, additional_productive_surplus_area_ha: row.additional_productive_surplus_area_ha, gross_site_area_ha: row.gross_site_area_ha, land_accounting: publicize(row.land_accounting), recurring_labour: publicize(row.recurring_labour), human_food_energy: publicize(row.human_food_energy), evidence_boundary: publicize(row.evidence_boundary), selection_rule: publicText(row.selection_rule)}));
  const transitionRows = (canonical.canonical.food_forest_transition.households ?? []).filter((row) => ['wetter_productive', 'ordinary_mesic', 'shallow_rocky_marginal'].includes(row.site)).map((row) => ({site: row.site, site_label: row.site_label, household: row.household, household_label: row.household_label, household_food_demand_gj_year: row.household_food_demand_gj_year, rows: row.transition.constant_annual_reserve.rows.map(pickTransition), transition_model: row.transition.constant_annual_reserve.description}));
  const presets = Object.entries(householdProfiles).map(([id, profile]) => ({id, label: profile.label, member_ids: profile.member_ids, members: profile.member_ids.map((memberId) => publicEer(canonical.canonical.human_energy.scenarios[memberId]))}));
  const regionalFoodDemandGJ = Number(foodCalibration.foodDemandBaseline?.totalFoodDemandGJ ?? 0);
  const regional = calculateGreyCarryingCapacityAdoption({eligibleHouseholds, eligiblePopulation, regionalFoodDemandGJ, eligibilityBasis: 'estimatedDwellingsWithGardenScaleAccess and corresponding population from the current dwelling-land proxy; not parcel ownership or biological site classification'});
  const siteMixVariants = {
    balanced: regional,
    favourable_heavy: calculateGreyCarryingCapacityAdoption({eligibleHouseholds, eligiblePopulation, regionalFoodDemandGJ, siteShares: {favourable: .5, ordinary: .3, marginal: .2}, eligibilityBasis: 'same garden-scale dwelling-land proxy; alternative explicit site-mix sensitivity'}),
    marginal_heavy: calculateGreyCarryingCapacityAdoption({eligibleHouseholds, eligiblePopulation, regionalFoodDemandGJ, siteShares: {favourable: .15, ordinary: .35, marginal: .5}, eligibilityBasis: 'same garden-scale dwelling-land proxy; alternative explicit site-mix sensitivity'})
  };
  return {
    contract_version: PRESENTATION_CONTRACT_VERSION,
    model_contract_version: CARRYING_CAPACITY_CONTRACT_VERSION,
    model_version: canonical.model_version,
    generated_at: generatedAt,
    units: {energy: 'MJ/day and GJ/year', land: 'ha', labour: 'hours/year', population: 'people'},
    metric_only_presentation: true,
    reference_profile: publicEer(calculateHealthCanadaEER(referenceProfile)),
    health_canada: {source: canonical.canonical.human_energy.source, scenarios: energyScenarios, activity_categories: ['inactive', 'low', 'active', 'very'], food_adult_equivalent: {gj_year: FOOD_ADULT_EQUIVALENT_GJ_YEAR, definition: 'Mean food-energy requirement of the representative low-activity adult woman and man; food-energy normalization only, not a land multiplier.'}, equation_note: 'The canonical equation is evaluated in its source form; this public presentation exposes energy in MJ and GJ only.'},
    site_classes: publicSites,
    household_profiles: householdProfiles,
    household_presets: presets,
    mature_rows: matureRows,
    transition_rows: transitionRows,
    heating: {source: heatingEvidence.source, audit: heatingEvidence.audit, cases: Object.fromEntries(Object.entries(heatingEvidence.cases).map(([id, row]) => [id, {useful_space_heating_gj_year: row.heat_loss.annual_useful_space_heating_gj, gross_wood_energy_gj_year: row.wood.gross_wood_energy_required_gj, dry_wood_tonnes_year: row.wood.approximate_dry_wood_tonnes}])), building_archetypes: Object.fromEntries(Object.entries(buildingArchetypes).map(([id, row]) => [id, {id, ...row}])), insulation_presets: Object.fromEntries(Object.entries(insulationPresets).map(([id, row]) => [id, {id, ...row}])), default_building: defaultBuilding(), labour_capacity_levels: labourCapacityLevels, model_notes: ['Building heating is calculated from form geometry, floor area, RSI envelope values, window loss, ventilation/infiltration, ECCC HDD, indoor temperature, heater efficiency and thermal bridges.', 'Building presets are transparent physical assumptions, not as-built surveys.']},
    woody_yields: {source: woodyEvidence.source, bands: woodyEvidence.bands, cases: woodyEvidence.cases},
    food_energy_evidence: {source: foodEvidence.source, rows: foodEvidence.rows.map((row) => ({id: row.id, crop: row.crop, category: row.category, food_gj_ha: row.food_gj_ha, protein_kg_ha: row.protein_kg_ha, fat_kg_ha: row.fat_kg_ha, carbohydrate_kg_ha: row.carbohydrate_kg_ha, evidence_type: row.evidence_type, canonical_status: row.canonical_status, source: row.source}))},
    perennial_food_evidence: {source: perennialEvidence.source, rows: perennialEvidence.rows.map(publicPerennialRow), mix: perennialEvidence.mix.map((row) => ({id: row.id, area_share: row.area_share, class: row.class, species: row.species, role: row.role, mature_food_gj_ha_year: row.mature_food_gj_ha_year, canonical_status: row.canonical_status})), central_mix: perennialEvidence.central_mix, mix_timeline: calculatePerennialMixTimeline({evidence: perennialEvidence}), evidence_limitations: perennialEvidence.evidence_limitations.map(publicText), research_updates: publicize(perennialEvidence.research_updates ?? [])},
    regional: {grey: {...publicRegional(regional), site_mix_variants: Object.fromEntries(Object.entries(siteMixVariants).map(([key, variant]) => [key, publicRegional(variant)]))}, land_access_proxy: {status: landAccessStatus, eligible_households: landAccessProxyAvailable ? eligibleHouseholds : null, eligible_population_people: landAccessProxyAvailable ? eligiblePopulation : null, source_file: 'grey-dwelling-land-access.json', caveat: 'Best current proxy only; Grey County does not yet have a validated parcel-level biological site-capability map. Regional outputs are zeroed when this proxy is unavailable rather than silently reusing stale data.'}},
    systemic_energy_contract: {contract_id: systemicEnergy.contract_id, schema_version: systemicEnergy.schema_version, producer: systemicEnergy.producer, fields: (systemicEnergy.fields ?? []).map((field) => ({field_id: field.field_id, evidence_status: field.evidence_status, source_date: field.source_date, uncertainty: field.uncertainty}))},
    solar: {status: 'conceptual_only', numerical_local_solar_budget: false, note: 'A defensible Owen Sound annual solar-radiation source and transformation chain have not yet been established; no photosynthetic efficiency or crop yield is invented here.'},
    methodology: {dependency_chain: ['person characteristics', 'Health Canada energy requirement', 'annual household food energy', 'balanced low-input food yield', 'annual bridge area', 'perennial transition and resilience reserve', 'mature productive land plus woody heating'], parallel_chains: {people: ['age, sex, height, weight, activity', 'MJ/day', 'GJ/year food', 'food-production area'], buildings: ['floor area, form, RSI envelope, leakage', 'GJ/year useful heat', 'gross woody energy', 'woody-production area']}, labour_note: 'Metabolic food demand and explicit assigned labour capacity are separate inputs. Sex, age, height, weight and activity do not infer agricultural capability.', land_accounting: 'Annual food, perennial food, heating and exclusive reserve are kept distinct; soil/water, wildlife, fibre and habitat functions are reported as overlapping multifunctional coverage.', custom_household_note: 'The browser imports pure canonical EER, balanced-food, building-heating and labour-capacity functions. Custom transition charts scale a canonical reference transition explicitly; household presets display full canonical transition rows.', external_input_note: 'Energy-condition multipliers are regional scenario overlays, not replacements for the biological carrying-capacity evidence model.'},
    sources: [{institution: 'Health Canada', title: 'Equations to Estimate Energy Requirement', url: canonical.canonical.human_energy.source, evidence_status: 'official equation'}, {institution: 'Living Region carrying-capacity package', title: 'Evidence summary and canonical household/site rows', url: 'packages/carrying-capacity/outputs/summary.json', evidence_status: 'generated canonical model'}, {institution: 'ECCC / Living Region', title: 'Owen Sound heating-degree-day and dwelling envelope case', url: 'packages/carrying-capacity/data/derived/evidence-heating.json', evidence_status: 'modelled case with climate normal'}, {institution: 'Living Region perennial evidence', title: 'Perennial yield and establishment evidence', url: 'packages/carrying-capacity/outputs/perennial-yield-evidence.md', evidence_status: 'mixed measured, extension and planning synthesis; see row status'}, {institution: 'Living Region evidence files', title: 'Balanced low-input food yields and woody biomass bands', url: 'packages/carrying-capacity/data/derived/', evidence_status: 'mixed measured/synthesized evidence; see row status'}]
  };
}
